Repository MegaMek/megamek, pull requests merged in 2020-12, with the labels that each got.

#2490 Add machine gun ammo types to the compatible list
  megamek/src/megamek/common/AmmoType.java
Labels: Bug

#2482 Update Equipment Extended Database CSV file
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/TechAdvancement.java
  megamek/src/megamek/common/weapons/lasers/ISLaserMedium.java
Labels: Data, Enhancement

#2489 MM XML Util: Array Writing Methods
  megamek/src/megamek/utils/MegaMekXmlUtil.java
Labels: Enhancement

#2508 Colour Selector Button
  megamek/src/megamek/client/ui/swing/ColourSelectorButton.java
Labels: Enhancement

#2504 Moving Color Names to PlayerColors
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java
  megamek/src/megamek/client/ui/swing/util/PlayerColors.java
  megamek/src/megamek/common/IPlayer.java
  megamek/src/megamek/server/ScenarioLoader.java
  megamek/src/megamek/server/Server.java
Labels: Enhancement

#2417 Fixed critical slot error in Right Arm of CPLT-C6
  megamek/data/mechfiles/mechs/3050U/Catapult CPLT-C6.mtf
  megamek/data/mechfiles/mechs/RS Unique/Hercules Julius.mtf
Labels: Data

#2509 AbstractIcon: Null Protection for ImageIcons and Separating Dialogs out from the Choosers beneath
  megamek/src/megamek/client/ui/swing/ChatLounge.java
  megamek/src/megamek/client/ui/swing/CustomPilotView.java
  megamek/src/megamek/client/ui/swing/ScenarioDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconChooserDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooserDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/PortraitChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/PortraitChooserDialog.java
  megamek/src/megamek/common/icons/AbstractIcon.java
Labels: Bug, Enhancement

#2518 Issue #2517: Ensure AmmoType::canSwitchToAmmo ignores munition types
  megamek/src/megamek/common/AmmoType.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
  megamek/unittests/megamek/common/AmmoTypeTest.java
Labels: Bug
