Repository MegaMek/megamek, pull requests merged in 2021-03, with the labels that each got.

#2689 Random Skill Generator: Fixing AND Comparison
  megamek/src/megamek/client/generator/RandomSkillsGenerator.java
Labels: Bug

#2660 2592: Random Army Creation Tech Level Max Index Comparison Issue
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
Labels: Bug

#2661 2272: Fixing Alt-Click on Building and Mouse Wheel Over Building/Bridge/Fuel Tank Not Clearing Tile
  megamek/src/megamek/client/ui/swing/BoardEditor.java
Labels: Bug, Map Editor

#2575 Test and refactor whydoomed
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/common/PlanetaryConditions.java
  megamek/unittests/megamek/common/PlanetaryConditionsTest.java
Labels: Test

#2691 Base Components
  .gitignore
  megamek/build.gradle
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_de.properties
  megamek/i18n/megamek/client/messages_en.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/mmconf/shared.properties
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/client/bot/ui/swing/BotGUI.java
  megamek/src/megamek/client/ui/baseComponents/AbstractButtonDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractScrollPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractSplitPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractTabbedPane.java
  megamek/src/megamek/client/ui/dialogs/helpDialogs/AbstractHelpDialog.java
  megamek/src/megamek/client/ui/dialogs/helpDialogs/BoardEditorHelpDialog.java
  megamek/src/megamek/client/ui/dialogs/helpDialogs/BotHelpDialog.java
  megamek/src/megamek/client/ui/dialogs/helpDialogs/MMReadMeHelpDialog.java
  megamek/src/megamek/client/ui/enums/DialogResult.java
  megamek/src/megamek/client/ui/preferences/JComboBoxPreference.java
  megamek/src/megamek/client/ui/preferences/JDoubleNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JIntNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JListPreference.java
  megamek/src/megamek/client/ui/preferences/JSplitPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTabbedPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTablePreference.java
  megamek/src/megamek/client/ui/preferences/JTextFieldPreference.java
  megamek/src/megamek/client/ui/preferences/JToggleButtonPreference.java
  megamek/src/megamek/client/ui/preferences/JWindowPreference.java
  megamek/src/megamek/client/ui/preferences/MMPreferences.java
  megamek/src/megamek/client/ui/preferences/PreferenceElement.java
  megamek/src/megamek/client/ui/preferences/PreferencesNode.java
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonHelpDialog.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/common/util/SharedConfiguration.java
Labels: Enhancement, UI

#2723 Base Components: Making One Touch Expandable Default for Split Panes
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractSplitPane.java
Labels: Enhancement

#2725 Issue #2722: Do not send IP addresses in chat by default
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/preference/IClientPreferences.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/commands/WhoCommand.java
Labels: Security

#2726 Issue #2722: Add a UI to enable/disable showing IPs in chat
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/common/preference/IClientPreferences.java
Labels: Security, Stable Backport Candidate

#2717 Java 11 Migration TODOs and isBlank Cleanup
  megamek/src/megamek/client/ui/preferences/JComboBoxPreference.java
  megamek/src/megamek/client/ui/preferences/JDoubleNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JIntNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JListPreference.java
  megamek/src/megamek/client/ui/preferences/JSplitPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTabbedPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTablePreference.java
  megamek/src/megamek/client/ui/preferences/JToggleButtonPreference.java
  megamek/src/megamek/client/ui/preferences/JWindowPreference.java
  megamek/src/megamek/client/ui/preferences/PreferenceElement.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/ImageList.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/icons/AbstractIcon.java
  megamek/src/megamek/common/util/StringUtil.java
Labels: Enhancement

#2688 Compute: Adding Individual Dice and Individual Rolls Methods
  megamek/src/megamek/common/Compute.java
Labels: Enhancement

#2752 Offboard Artillery Target Not Found NPE
  megamek/src/megamek/client/ui/swing/boardview/BoardView1.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/IGame.java
  megamek/src/megamek/common/actions/AbstractAttackAction.java
Labels: Bug

#2570 AbstractIcon: Full Camouflage Implementation
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/ChatLounge.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/ScenarioDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconChooserDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooserDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooserTree.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/PortraitChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/PortraitChooserDialog.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EntityListFile.java
  megamek/src/megamek/common/IPlayer.java
  megamek/src/megamek/common/MULParser.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/icons/AbstractIcon.java
  megamek/src/megamek/common/icons/Camouflage.java
  megamek/src/megamek/server/ScenarioLoader.java
  megamek/src/megamek/server/Server.java
Labels: Enhancement
