Repository MegaMek/megamek, pull requests merged in 2021-09, with the labels that each got.

#3123 JToggleButtonPreference: Swapping to using doClick
  megamek/src/megamek/client/ui/preferences/JToggleButtonPreference.java
Labels: Enhancement, GUI

#3127 MekHQ Campaign Preset Rework: Standardized Game Options File I/O
  megamek/src/megamek/common/options/GameOptions.java
Labels: Enhancement

#3111 2854: Only skip the invalid unit when not allowing illegal designs
  megamek/src/megamek/server/Server.java
Labels: Bug

#3130 MegaMek XML Util: Fixing Two Escaping Issues
  megamek/src/megamek/utils/MegaMekXmlUtil.java
Labels: Bug, Blocker

#2581 MegaMek XML Util: Adding Proper Parsing Methods
  megamek/src/megamek/utils/MegaMekXmlUtil.java
Labels: Enhancement

#3131 3089: Fixing messages implementation to handle localization
  megamek/i18n/megamek/client/bot/messages_en.properties
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_en.properties
  megamek/i18n/megamek/common/options/messages_en.properties
  megamek/i18n/megamek/server/messages_en.properties
Labels: Bug, Blocker

#3132 Princess Player NPE
  megamek/src/megamek/client/bot/princess/Precognition.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/IGame.java
Labels: Bug, Princess

#3114 AbstractIcon: Adding Force Camouflage to MegaMek
  megamek/src/megamek/client/ratgenerator/ForceDescriptor.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/force/Force.java
  megamek/src/megamek/common/force/Forces.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/ServerLobbyHelper.java
Labels: Bug, Enhancement

#3143 Adjusted FWL availability for Moltke MBT per current MUL data.
  megamek/data/forcegenerator/3078.xml
  megamek/data/forcegenerator/3082.xml
  megamek/data/forcegenerator/3085.xml
  megamek/data/forcegenerator/3100.xml
  megamek/data/forcegenerator/3135.xml
  megamek/data/forcegenerator/3145.xml
  megamek/data/forcegenerator/3150.xml
Labels: Data

#3161 Corrected MUL Force Saving
  megamek/src/megamek/common/force/Forces.java
Labels: Bug, Blocker

#3167 Tripod 'Mech Center Leg Actuator Damage Customization
  megamek/src/megamek/client/ui/swing/UnitEditorDialog.java
Labels: Bug

#3168 Array bounds protecting Entity::getCritical
  megamek/src/megamek/common/Entity.java
Labels: Bug

#3169 3133: Adding before round 1 deployment option
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java
Labels: Bug, GUI
