Repository MegaMek/megamek, pull requests merged in 2021-06, with the labels that each got.

#2895 MHQ 2529: Adding the ability to set ignore pilot BV for a MechView
  megamek/src/megamek/common/MechView.java
Labels: Bug

#2932 2917: Fixing Structured_Water directory reference
  megamek/data/images/hexes/saxarba/Structured_Water - Saxarba.tileinc
Labels: Bug

#2948 Minimap
  megamek/data/mapsetup/TheJungle 90x68.xml
  megamek/data/mapsetup/TheJungle 90x85.xml
  megamek/data/mapsetup/TheMoon 60x51.xml
  megamek/src/megamek/client/ui/minimap/MiniMapUnitSymbols.java
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MiniMap.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/Hex.java
  megamek/src/megamek/common/IHex.java
Labels: UI

#2962 Connection Watchdog: Renaming File to Match Class
  megamek/src/megamek/server/ConnectionWatchdog.java
Labels: Bug

#2967 2960: Fixing non-basic letters in the new camouflage setup
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/2nd Liao Dragoons.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Ishara's Grenadiers.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Kamakura's Hussars.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Liao Reserves.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Renshield's Dragoons.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Syn's Hussars.jpg
  megamek/data/images/camo/Capellan Confederation/Liao Chang-Cheng/Vong's Grenadiers.jpg
  megamek/data/images/camo/Magistracy of Canopus/Chasseurs a Cheval/1st Canopian Light Horse.jpg
  megamek/data/images/camo/Magistracy of Canopus/Chasseurs a Cheval/2nd Canopian Light Horse.jpg
  megamek/data/images/camo/Magistracy of Canopus/Chasseurs a Cheval/3rd Canopian Light Horse.jpg
  megamek/data/images/camo/Pirates/Shen-se Tian.jpg
Labels: Bug, Data

#2971 Fixing the Magistracy of Canopus Planetary Militia Force Generator Faction
  megamek/data/forcegenerator/factions.xml
Labels: Data
