Repository MegaMek/megamek, pull requests merged in 2021-08, with the labels that each got.

#3046 Update Bombardier BMB-14K.mtf
  megamek/data/mechfiles/mechs/3050U/Bombardier BMB-14K.mtf
Labels: Data

#3028 Base Components: AbstractPanel
  megamek/src/megamek/client/ui/baseComponents/AbstractPanel.java
Labels: Enhancement, GUI

#2938 1050: UserData: MegaMek data/names Implementation
  .gitignore
  megamek/build.gradle
  megamek/src/megamek/MegaMekConstants.java
  megamek/src/megamek/client/generator/RandomCallsignGenerator.java
  megamek/src/megamek/client/generator/RandomNameGenerator.java
  megamek/src/megamek/common/Configuration.java
  megamek/unittests/megamek/common/ConfigurationTests.java
  megamek/userdata/README.md
Labels: Enhancement

#3072 Swapping Hidden Units to be default on, as per Discord discussion
  megamek/src/megamek/common/options/GameOptions.java
Labels: Enhancement

#3078 3042: Properly Set Anti-Mek Skill For Battle Armour and Infantry
  megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
Labels: Bug

#3082 AbstractUnitSelectorDialog: Properly Catching NPEs and other MechFileParser Exceptions in getSelectedEntity
  megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java
Labels: Bug

#3094 Adding a subject to Report 3033
  megamek/src/megamek/server/Server.java
Labels: Bug

#3097 MHQ 2754: Adding a way to clear Narc/iNarc
  megamek/src/megamek/common/Entity.java
Labels: Bug

#3099 Update Anubis ABS-3MC.mtf
  megamek/data/mechfiles/mechs/XTRs/Periphery/Anubis ABS-3MC.mtf
Labels: Data

#3100 Fix Quad Location Keys
  megamek/data/mechfiles/mechs/3067/Blue Flame BLF-21.mtf
  megamek/data/mechfiles/mechs/3145/Republic/Celerity CLR-04-R.mtf
  megamek/data/mechfiles/mechs/3145/Republic/Celerity CLR-05-X.mtf
  megamek/data/mechfiles/mechs/Operation Klondike/Daedalus GTX2 (Militarized).mtf
  megamek/data/mechfiles/mechs/Operation Klondike/Daedalus GTX2A Stevedore.mtf
  megamek/data/mechfiles/mechs/Operation Klondike/Daedalus GTX2B Navvy.mtf
  megamek/data/mechfiles/mechs/Operation Klondike/Harvester Ant KIC-3M-B AgroMech (LRM).mtf
  megamek/data/mechfiles/mechs/TR Vehicle Annex/Harvester Ant KIC-3M-B AgroMech MOD.mtf
Labels: Data

#3079 Skill Generation Rework
  megamek/i18n/megamek/client/messages_en.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/generator/RandomSkillsGenerator.java
  megamek/src/megamek/client/generator/enums/SkillGeneratorMethod.java
  megamek/src/megamek/client/generator/enums/SkillGeneratorType.java
  megamek/src/megamek/client/generator/skillGenerators/AbstractSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ConstantSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ModifiedConstantSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ModifiedTotalWarfareSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/TaharqaSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/TotalWarfareSkillGenerator.java
  megamek/src/megamek/client/ui/baseComponents/AbstractPanel.java
  megamek/src/megamek/client/ui/panels/SkillGenerationOptionsPanel.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CustomPilotView.java
  megamek/src/megamek/client/ui/swing/ForceGeneratorViewUi.java
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
  megamek/src/megamek/client/ui/swing/RandomNameDialog.java
  megamek/src/megamek/client/ui/swing/RandomSkillDialog.java
  megamek/src/megamek/client/ui/swing/SkillGenerationDialog.java
  megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerSettingsDialog.java
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: Bug, Enhancement

#3122 Nova Net Command: Improving error chat replies
  megamek/src/megamek/server/commands/AssignNovaNetServerCommand.java
Labels: Enhancement

#3124 Preferences: Ignore Missing File For Logging
  megamek/src/megamek/client/ui/preferences/MMPreferences.java
Labels: Enhancement

#3096 Russian names cleanup
  megamek/data/names/femaleGivenNames.csv
  megamek/data/names/maleGivenNames.csv
  megamek/data/names/surnames.csv
Labels: Enhancement, Data
