Repository MegaMek/megamek, pull requests merged in 2021-11, with the labels that each got.

#3112 Update Atlas III AS7-D3.mtf
  megamek/data/mechfiles/mechs/3145/Davion/Atlas III AS7-D3.mtf
  megamek/data/mechfiles/mechs/Golden Century/Omni-Corvis B.mtf
Labels: Data

#3249 Ammo/Weapon techbase mismatch fixes + one instance of missing ammo
  megamek/data/mechfiles/mechs/3145/NTNU RS/Deimos E.mtf
  megamek/data/mechfiles/mechs/ER 2750/Victor VTR-9B (Shoji).mtf
  megamek/data/mechfiles/mechs/Golden Century/Emperor EMP-6A-EC.mtf
  megamek/data/mechfiles/mechs/Recognition Guide ilClan/Vol 18/Jenner IIC 3.mtf
  megamek/data/mechfiles/mechs/Recognition Guide ilClan/Vol 7/Koshi (Mist Lynx) I.mtf
  megamek/data/mechfiles/mechs/Recognition Guide ilClan/Vol 8/Dragonfly (Viper) R.mtf
  megamek/data/mechfiles/mechs/Shattered Fortress/Templar III TLR2-J Arthur.mtf
  megamek/data/mechfiles/mechs/Turning Points/OTP WidowMaker Absorption/Highlander HGN-732 (Jorgensson).mtf
  megamek/data/mechfiles/vehicles/3085u/Cutting Edge/Zephyros Infantry Support Vehicle.blk
  megamek/data/mechfiles/vehicles/3145/NTNU/Bolla Stealth Tank D.blk
Labels: Data

#3270 Updating Flat Look And Feel from 0.26 to 1.6.4
  megamek/build.gradle
Labels: Enhancement

#3271 IBoardView: Replacing with BoardView
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/ui/IBoardView.java
  megamek/src/megamek/client/ui/swing/AbstractPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/AccessibilityWindow.java
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ChatterBox2.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/DeployMinefieldDisplay.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/client/ui/swing/MiniMap.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/OffBoardTargetOverlay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/Ruler.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TurretFacingDialog.java
  megamek/src/megamek/client/ui/swing/UnitOverview.java
  megamek/src/megamek/client/ui/swing/boardview/AbstractWreckSprite.java
  megamek/src/megamek/client/ui/swing/boardview/AttackSprite.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/C3Sprite.java
  megamek/src/megamek/client/ui/swing/boardview/CursorSprite.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/FieldofFireSprite.java
  megamek/src/megamek/client/ui/swing/boardview/FiringSolutionSprite.java
  megamek/src/megamek/client/ui/swing/boardview/FlareSprite.java
  megamek/src/megamek/client/ui/swing/boardview/FlyOverSprite.java
  megamek/src/megamek/client/ui/swing/boardview/FovHighlightingAndDarkening.java
  megamek/src/megamek/client/ui/swing/boardview/GhostEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/HexDrawUtilities.java
  megamek/src/megamek/client/ui/swing/boardview/HexSprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricSprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricWreckSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovementEnvelopeSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovementModifierEnvelopeSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovementSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovingEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/Sprite.java
  megamek/src/megamek/client/ui/swing/boardview/StepSprite.java
  megamek/src/megamek/client/ui/swing/boardview/TextMarkerSprite.java
  megamek/src/megamek/client/ui/swing/boardview/VTOLAttackSprite.java
  megamek/src/megamek/client/ui/swing/boardview/WreckSprite.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/MekForceTreeRenderer.java
  megamek/src/megamek/client/ui/swing/lobby/MekTableModel.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/tileset/TilesetManager.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
Labels: Refactoring

#3281 Updating Commons-Text to 1.9 from 1.8.
  megamek/build.gradle
Labels: Enhancement

#3282 CommonConstants: Interface Removal
  megamek/src/megamek/common/CommonConstants.java
  megamek/src/megamek/common/EntityListFile.java
  megamek/src/megamek/common/WeaponOrderHandler.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/UnitStatusFormatter.java
Labels: Bug, Refactoring

#3276 ITerrainFactory and ITerrain: Removing Interfaces
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/tileset/HexTileset.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Building.java
  megamek/src/megamek/common/Hex.java
  megamek/src/megamek/common/IHex.java
  megamek/src/megamek/common/ITerrain.java
  megamek/src/megamek/common/ITerrainFactory.java
  megamek/src/megamek/common/LosEffects.java
  megamek/src/megamek/common/Terrain.java
  megamek/src/megamek/common/TerrainFactory.java
  megamek/src/megamek/common/Terrains.java
  megamek/src/megamek/common/util/BoardUtilities.java
  megamek/src/megamek/common/util/CityBuilder.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectHomingHandler.java
  megamek/src/megamek/common/weapons/WeaponHandler.java
  megamek/src/megamek/server/ElevatorProcessor.java
  megamek/src/megamek/server/GeyserProcessor.java
  megamek/src/megamek/server/QuicksandProcessor.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/ServerHelper.java
  megamek/src/megamek/server/SmokeCloud.java
  megamek/src/megamek/server/SmokeProcessor.java
  megamek/src/megamek/server/WeatherProcessor.java
  megamek/src/megamek/test/HexSetTest.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
Labels: Enhancement
