Repository MegaMek/megamek, pull requests merged in 2021-02, with the labels that each got.

#2627 Accessibility Window Shortcut
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
Labels: Accessibility

#2628 Scrollable Accessibility Window
  megamek/src/megamek/client/ui/swing/AccessibilityWindow.java
Labels: Accessibility

#2630 Fixing Infantry TRO Secondary Weapon Name
  megamek/src/megamek/common/templates/InfantryTROView.java
Labels: Bug

#2631 2625: Preventing Key Bindings when using the Accessibility Window
  megamek/src/megamek/client/ui/swing/AccessibilityWindow.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
Labels: Accessibility, Bug

#2638 Fixing MRM10/MRM20 Triple/Single Images
  megamek/data/images/units/mechset.txt
Labels: Data

#2640 Turret data fixes
  megamek/data/images/units/mechset.txt
  megamek/data/mechfiles/ge/Clan/Autocannons/ProtoAC/CLPROTO2 Turret (Quad).blk
  megamek/data/mechfiles/ge/Clan/Autocannons/ProtoAC/CLPROTO4 Turret (Quad).blk
Labels: Data

#2642 2639: Melee Specialist SPA Description Uses Internal Name
  megamek/src/megamek/common/Compute.java
Labels: Bug

#2649 Issue #2625: Change the default toggle chat to backquote / grave
  megamek/docs/Default Key Binds.txt
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
Labels: Accessibility

#2682 2681: Fixing GameTurn Entity Check NPE
  megamek/src/megamek/common/GameTurn.java
Labels: Bug

#2683 2528: Undo during movement recalculates LOS
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
Labels: Bug

#2686 Distance Null Coordinate NPE
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/Coords.java
  megamek/src/megamek/common/Entity.java
Labels: Bug
