Repository MegaMek/megamek, pull requests merged in 2021-01, with the labels that each got.

#2531 MekHQ 1727: Colour Camouflage
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/princess/Precognition.java
  megamek/src/megamek/client/ui/ITilesetManager.java
  megamek/src/megamek/client/ui/swing/ChatLounge.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MiniMap.java
  megamek/src/megamek/client/ui/swing/ScenarioDialog.java
  megamek/src/megamek/client/ui/swing/boardview/AttackSprite.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView1.java
  megamek/src/megamek/client/ui/swing/boardview/C3Sprite.java
  megamek/src/megamek/client/ui/swing/boardview/ECMEffects.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/FlyOverSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovementSprite.java
  megamek/src/megamek/client/ui/swing/boardview/VTOLAttackSprite.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/AbstractIconPanel.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooser.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooserDialog.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamoChooserTree.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/CamouflagePanel.java
  megamek/src/megamek/client/ui/swing/dialog/imageChooser/PortraitPanel.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/tileset/EntityImage.java
  megamek/src/megamek/client/ui/swing/tileset/TilesetManager.java
  megamek/src/megamek/client/ui/swing/util/ColorParser.java
  megamek/src/megamek/client/ui/swing/util/PlayerColors.java
  megamek/src/megamek/client/ui/swing/util/PlayerColour.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/IPlayer.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/Report.java
  megamek/src/megamek/common/icons/AbstractIcon.java
  megamek/src/megamek/common/icons/Camouflage.java
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/preference/IClientPreferences.java
  megamek/src/megamek/common/weapons/MekMortarAirburstHandler.java
  megamek/src/megamek/common/weapons/MissileMineClearanceHandler.java
  megamek/src/megamek/server/ScenarioLoader.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/utils/GenerateGenericIconList.java
Labels: Bug, Enhancement

#2554 Fix TargetRoll description if negative modifier is first
  megamek/src/megamek/common/TargetRoll.java
  megamek/unittests/megamek/common/TargetRollTest.java
Labels: Bug, Test

#2556 Remove duplicate boards
  megamek/data/boards/unofficial/SimonLandmineMaps/WWE2018 Terrain Set/16x17 WWE2018 BattleTech.board
  megamek/data/boards/unofficial/SimonLandmineMaps/WWE2018 Terrain Set/16x17 WWE2018 DigSite.board
  megamek/data/boards/unofficial/SimonLandmineMaps/WWE2018 Terrain Set/16x17 WWE2018 LargeLakes.board
  megamek/data/boards/unofficial/SimonLandmineMaps/WWE2018 Terrain Set/16x17 WWE2018 ScatteredWoods.board
  megamek/data/boards/unofficial/SimonLandmineMaps/WWE2018 Terrain Set/32x34 WWE2018 DigDefendOrDie.board
Labels: Data

#2568 1967/1968: Swapping to use ImageIO.read() For Zipped File reads
  megamek/src/megamek/common/util/fileUtils/ImageFileFactory.java
Labels: Bug

#2567 Colour Camouflage: Fixing Colour Camouflage Tint Application and Colour Setter
  megamek/src/megamek/client/ui/ITilesetManager.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/tileset/EntityImage.java
  megamek/src/megamek/client/ui/swing/tileset/TilesetManager.java
  megamek/src/megamek/common/Player.java
Labels: Bug

#2589 2584: Player ComboBox now properly updates on load
  megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
Labels: Bug

#2607 Issue #2580: Fix non-unique IDs for Buildings
  megamek/src/megamek/common/Building.java
Labels: Bug
