Repository MegaMek/megamek, pull requests merged in 2022-04, with the labels that each got.

#3553 New names
  megamek/data/names/femaleGivenNames.csv
  megamek/data/names/maleGivenNames.csv
Labels: Data, Conflicts

#3540 DockingCollar Refactor
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/common/BattleArmorHandles.java
  megamek/src/megamek/common/Bay.java
  megamek/src/megamek/common/DockingCollar.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/TankTrailerHitch.java
  megamek/src/megamek/common/Transporter.java
  megamek/src/megamek/common/TroopSpace.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKJumpshipFile.java
  megamek/src/megamek/common/loaders/BLKWarshipFile.java
Labels: Refactoring

#3554 StringUtility: Renaming isNullOrEmpty to the proper isNullOrBlank
  megamek/src/megamek/Version.java
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/HexHasPathToCenterCache.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/FiringPlan.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/swing/RandomMapDialog.java
  megamek/src/megamek/client/ui/swing/ResizeMapDialog.java
  megamek/src/megamek/client/ui/swing/gameConnectionDialogs/AbstractGameConnectionDialog.java
  megamek/src/megamek/client/ui/swing/widget/VerifiableTextField.java
  megamek/src/megamek/codeUtilities/StringUtility.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EntityListFile.java
  megamek/src/megamek/common/QuirkEntry.java
  megamek/src/megamek/common/util/AddBotUtil.java
  megamek/src/megamek/common/util/EmailService.java
  megamek/src/megamek/common/util/StringUtil.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
Labels: Bug, Refactoring

#3569 Fixing Freemarker version initialization
  megamek/src/megamek/common/templates/TemplateConfiguration.java
Labels: Bug

#3581 3576: Fixing Destroyed Squadron Kill Assignment IllegalArgumentException
  megamek/src/megamek/server/Server.java
Labels: Bug, Aerospace

#3591 Fixing MegaMek log paths
  ISSUE_TEMPLATE.md
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_de.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/src/megamek/common/Report.java
  megamek/src/megamek/server/commands/FixElevationCommand.java
Labels: Bug

#3593 Moving SerialKiller to constant file path
  megamek/src/megamek/MMConstants.java
  megamek/src/megamek/common/net/marshall/NativeSerializationMarshaller.java
Labels: Enhancement, Refactoring

#3596 Connection Rework Phase One
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/princess/Precognition.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/common/event/GameCFREvent.java
  megamek/src/megamek/common/net/AbstractConnection.java
  megamek/src/megamek/common/net/ConnectedEvent.java
  megamek/src/megamek/common/net/ConnectionEvent.java
  megamek/src/megamek/common/net/ConnectionListener.java
  megamek/src/megamek/common/net/DisconnectedEvent.java
  megamek/src/megamek/common/net/Packet.java
  megamek/src/megamek/common/net/PacketReceivedEvent.java
  megamek/src/megamek/common/net/enums/ConnectionEventType.java
  megamek/src/megamek/common/net/enums/PacketCommand.java
  megamek/src/megamek/common/net/events/AbstractConnectionEvent.java
  megamek/src/megamek/common/net/events/ConnectedEvent.java
  megamek/src/megamek/common/net/events/DisconnectedEvent.java
  megamek/src/megamek/common/net/events/PacketReceivedEvent.java
  megamek/src/megamek/common/net/marshall/NativeSerializationMarshaller.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/ServerLobbyHelper.java
  megamek/src/megamek/server/commands/KickCommand.java
  megamek/src/megamek/test/PacketTool.java
Labels: Bug, Enhancement, Refactoring, Blocker
