Repository MegaMek/megamek, pull requests merged in 2022-08, with the labels that each got.

#3853 Base Components: AbstractScrollablePanel
  megamek/src/megamek/client/ui/baseComponents/AbstractScrollablePanel.java
Labels: Enhancement, GUI

#3843 Fix #3135 Shadow rendering darkening most buildings by rendering 'on top'.
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
Labels: Enhancement

#3838 Version: Make the Default the Minimum, not Maximum
  megamek/src/megamek/Version.java
Labels: Bug

#3869 Gradle 7.5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Build / CI

#3872 Fixing Gradle Build Deprecations
  megamek/build.gradle
Labels: Build / CI
