Repository MegaMek/megamek, pull requests merged in 2022-12, with the labels that each got.

#4024 4022: Fixing Uncaught NPE when Address Bind is Already in Use
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
Labels: Blocker

#3996 MMXMLUtility: Removing Deprecated Methods
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/utilities/xml/MMXMLUtility.java
Labels: Enhancement

#4029 Fixing Hermes Fasther Typo
  megamek/data/mechfiles/mechs/3039u/Hermes HER-1A.mtf
  megamek/data/mechfiles/mechs/3039u/Hermes HER-1B.mtf
Labels: Bug, Data

#4023 4021: Preventing Save Game Loading Player Name NPE
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/Version.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/weapons/ACAPHandler.java
  megamek/src/megamek/common/weapons/AmmoWeaponHandler.java
  megamek/src/megamek/common/weapons/BayWeaponHandler.java
  megamek/src/megamek/common/weapons/CLIATMHandler.java
  megamek/src/megamek/common/weapons/FireExtinguisherHandler.java
  megamek/src/megamek/common/weapons/FlamerHandler.java
  megamek/src/megamek/common/weapons/MissileWeaponHandler.java
  megamek/src/megamek/common/weapons/Weapon.java
  megamek/src/megamek/common/weapons/WeaponHandler.java
  megamek/src/megamek/common/weapons/autocannons/ACWeapon.java
  megamek/src/megamek/common/weapons/lasers/ISERLaserLarge.java
  megamek/src/megamek/common/weapons/prototypes/ISERLaserLargePrototype.java
  megamek/src/megamek/server/Server.java
Labels: Blocker

#3969 RFE 426 overlay for Planetary Conditions
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/i18n/megamek/common/messages_es.properties
  megamek/i18n/megamek/common/messages_ru.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/PlanetaryConditionsOverlay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
  megamek/src/megamek/common/PlanetaryConditions.java
Labels: Enhancement, GUI

#4048 4043: Fixing No Server NPEs
  megamek/src/megamek/common/MechSummaryCache.java
  megamek/src/megamek/common/weapons/autocannons/ACWeapon.java
  megamek/src/megamek/common/weapons/lasers/ISERLaserLarge.java
  megamek/src/megamek/common/weapons/prototypes/ISERLaserLargePrototype.java
  megamek/src/megamek/server/Server.java
Labels: Bug, Blocker

#4049 Player Java 17 Support
  .github/workflows/ci.yml
  .github/workflows/code-coverage.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/update-maven-repo.yml
  .github/workflows/validate-boards.yml
  megamek/build.gradle
Labels: Build / CI

#4053 Fixes #3977 Incorrect introduction date for Hoplite-4B
  megamek/data/mechfiles/mechs/3050U/Hoplite HOP-4B.mtf
Labels: Data

#4057 allow report display split pane to resize
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
Labels: Bug, GUI

#4055 fix some gui scale issues
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/boardview/KeyBindingsOverlay.java
  megamek/src/megamek/client/ui/swing/boardview/PlanetaryConditionsOverlay.java
Labels: Bug, GUI, Refactoring

#4054 Code cleanup for #4000
  megamek/src/megamek/server/ServerHelper.java
Labels: Refactoring, For New Dev Cycle

#4046 Issue #2652 TacOps BA crits
  megamek/src/megamek/common/BattleArmor.java
  megamek/src/megamek/common/weapons/infantry/InfantryWeaponHandler.java
Labels: Errata, For New Dev Cycle

#4045 BoardDimensions Cleanup
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/BoardDimensions.java
  megamek/unittests/megamek/common/BoardDimensionsTests.java
Labels: Refactoring, For New Dev Cycle

#4052 Issue 2945: RHS failure chance errata
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/ServerHelper.java
Labels: Errata, For New Dev Cycle

#4040 Updating XStream to 1.4.19 from 1.4.14
  megamek/build.gradle
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/common/util/SerializationHelper.java
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/Server.java
Labels: Enhancement, Security, Build / CI, For New Dev Cycle

#4056 Game Phase Simplification
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/ui/swing/BotGUI.java
  megamek/src/megamek/client/commands/FireCommand.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/dialogs/BotConfigTargetHexDialog.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/DeployMinefieldDisplay.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/ForceGeneratorViewUi.java
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/OffBoardTargetOverlay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/FovHighlightingAndDarkening.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/SystemPanel.java
  megamek/src/megamek/client/ui/swing/util/TurnTimer.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/Bay.java
  megamek/src/megamek/common/Dropship.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/FighterSquadron.java
  megamek/src/megamek/common/Infantry.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/actions/WeaponAttackAction.java
  megamek/src/megamek/common/weapons/ArtilleryBayWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/ArtilleryBayWeaponIndirectHomingHandler.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectHomingHandler.java
  megamek/src/megamek/common/weapons/CapitalMissileBearingsOnlyHandler.java
  megamek/src/megamek/common/weapons/WeaponHandler.java
  megamek/src/megamek/common/weapons/artillery/ArtilleryWeapon.java
  megamek/src/megamek/common/weapons/bayweapons/ArtilleryBayWeapon.java
  megamek/src/megamek/server/GameManager.java
Labels: Refactoring, For New Dev Cycle

#4050 Replacing Deprecated Applet Sound Use
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/ClientGUI.java
Labels: Enhancement, Refactoring, For New Dev Cycle

#4051 Tearing out EncodeControl
  megamek/src/megamek/client/bot/Messages.java
  megamek/src/megamek/client/generator/enums/SkillGeneratorMethod.java
  megamek/src/megamek/client/generator/enums/SkillGeneratorType.java
  megamek/src/megamek/client/ui/Messages.java
  megamek/src/megamek/client/ui/baseComponents/AbstractButtonDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractPanel.java
  megamek/src/megamek/client/ui/baseComponents/AbstractScrollPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractSplitPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractTabbedPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractValidationButtonDialog.java
  megamek/src/megamek/client/ui/dialogs/AbstractIconChooserDialog.java
  megamek/src/megamek/common/EntityMovementMode.java
  megamek/src/megamek/common/EquipmentMessages.java
  megamek/src/megamek/common/Messages.java
  megamek/src/megamek/common/ReportMessages.java
  megamek/src/megamek/common/enums/BasementType.java
  megamek/src/megamek/common/enums/GamePhase.java
  megamek/src/megamek/common/enums/SkillLevel.java
  megamek/src/megamek/common/enums/WeaponSortOrder.java
  megamek/src/megamek/common/options/Messages.java
  megamek/src/megamek/common/util/EncodeControl.java
  megamek/src/megamek/server/Messages.java
Labels: Refactoring, For New Dev Cycle

#4071 Allow Deserializing GameTurn Children
  megamek/src/megamek/common/util/SerializationHelper.java
Labels: Blocker
