Repository MegaMek/megamek, pull requests merged in 2022-09, with the labels that each got.

#3887 Excised Rumble Seat
  megamek/data/canonUnitQuirks.xml
  megamek/i18n/megamek/common/options/messages.properties
Labels: Data

#3882 Base Components: DefaultScrollablePanel
  megamek/src/megamek/client/ui/baseComponents/AbstractPanel.java
  megamek/src/megamek/client/ui/baseComponents/DefaultScrollablePanel.java
Labels: Enhancement, GUI

#3908 Connections Rework: Logging Modernization
  megamek/src/megamek/common/net/connections/AbstractConnection.java
  megamek/src/megamek/common/net/connections/DataStreamConnection.java
  megamek/src/megamek/common/net/marshalling/PacketMarshaller.java
  megamek/src/megamek/common/net/marshalling/PacketMarshallerFactory.java
Labels: Bug, Enhancement, Refactoring
