Repository MegaMek/megamek, pull requests merged in 2022-11, with the labels that each got.

#3988 MMXMLUtility: Removing Deprecated Methods
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/utilities/xml/MMXMLUtility.java
Labels: Enhancement

#3997 MHQ 3489: Fixing Missing DockingCollar Handling in Load
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/server/GameManager.java
Labels: Bug

#4009 3939: Prevent Null Entities in a Bay's Loaded Units
  megamek/src/megamek/common/Bay.java
Labels: Bug

#3987 Fixes #3984 Stuka-K5b2 data issues
  megamek/data/mechfiles/fighters/Operation Klondike/Stuka STU-K5b.blk
  megamek/data/mechfiles/fighters/Operation Klondike/Stuka STU-K5b2.blk
Labels: Data

#3986 Fixes #3985 ER Small Pulse Laser Incorrect Aerospace Range
  megamek/src/megamek/common/weapons/lasers/CLERPulseLaserSmall.java
Labels: Data

#3998 MMConstants: Isolate Font Constants
  megamek/src/megamek/SuiteConstants.java
  megamek/src/megamek/client/ui/swing/AccessibilityWindow.java
  megamek/src/megamek/client/ui/swing/AdvancedSearchDialog.java
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ChatterBox.java
  megamek/src/megamek/client/ui/swing/ChatterBox2.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/MMToggleButton.java
  megamek/src/megamek/client/ui/swing/UnitFailureDialog.java
  megamek/src/megamek/client/ui/swing/UnitOverview.java
  megamek/src/megamek/client/ui/swing/alphaStrike/ConfigurableASCardPanel.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/FiringSolutionSprite.java
  megamek/src/megamek/client/ui/swing/boardview/GhostEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricSprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricWreckSprite.java
  megamek/src/megamek/client/ui/swing/boardview/KeyBindingsOverlay.java
  megamek/src/megamek/client/ui/swing/boardview/MovingEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/StepSprite.java
  megamek/src/megamek/client/ui/swing/boardview/TextMarkerSprite.java
  megamek/src/megamek/client/ui/swing/boardview/WreckSprite.java
  megamek/src/megamek/client/ui/swing/calculationReport/TextCalculationReport.java
  megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java
  megamek/src/megamek/client/ui/swing/lobby/MapPreviewButton.java
  megamek/src/megamek/client/ui/swing/lobby/MekForceTreeRenderer.java
  megamek/src/megamek/client/ui/swing/lobby/TeamOverviewPanel.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/client/ui/swing/unitSelector/TWAdvancedSearchPanel.java
  megamek/src/megamek/client/ui/swing/util/UIUtil.java
  megamek/src/megamek/client/ui/swing/widget/AeroMapSet.java
  megamek/src/megamek/client/ui/swing/widget/ArmlessMechMapSet.java
  megamek/src/megamek/client/ui/swing/widget/BattleArmorMapSet.java
  megamek/src/megamek/client/ui/swing/widget/CapitalFighterMapSet.java
  megamek/src/megamek/client/ui/swing/widget/GeneralInfoMapSet.java
  megamek/src/megamek/client/ui/swing/widget/InfantryMapSet.java
  megamek/src/megamek/client/ui/swing/widget/JumpshipMapSet.java
  megamek/src/megamek/client/ui/swing/widget/LargeSupportTankMapSet.java
  megamek/src/megamek/client/ui/swing/widget/MechMapSet.java
  megamek/src/megamek/client/ui/swing/widget/PilotMapSet.java
  megamek/src/megamek/client/ui/swing/widget/ProtomechMapSet.java
  megamek/src/megamek/client/ui/swing/widget/QuadMapSet.java
  megamek/src/megamek/client/ui/swing/widget/SpheroidMapSet.java
  megamek/src/megamek/client/ui/swing/widget/SquadronMapSet.java
  megamek/src/megamek/client/ui/swing/widget/SuperHeavyTankMapSet.java
  megamek/src/megamek/client/ui/swing/widget/TankMapSet.java
  megamek/src/megamek/client/ui/swing/widget/TripodMechMapSet.java
  megamek/src/megamek/client/ui/swing/widget/VTOLMapSet.java
  megamek/src/megamek/client/ui/swing/widget/WarshipMapSet.java
  megamek/src/megamek/common/alphaStrike/cardDrawer/ASCard.java
Labels: Accessibility, Refactoring
