Repository MegaMek/megamek, pull requests merged in 2022-06, with the labels that each got.

#3672 Excised No Torso Twist & Replaced Quirks
  megamek/data/canonUnitQuirks.xml
  megamek/i18n/megamek/common/options/messages.properties
Labels: Data

#3615 Fixing all Assert Usages
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/TestBot.java
  megamek/src/megamek/client/bot/princess/Precognition.java
  megamek/src/megamek/client/ratgenerator/UnitTable.java
  megamek/src/megamek/client/ui/baseComponents/AbstractButtonDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
  megamek/src/megamek/client/ui/baseComponents/AbstractPanel.java
  megamek/src/megamek/client/ui/baseComponents/AbstractScrollPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractSplitPane.java
  megamek/src/megamek/client/ui/baseComponents/AbstractTabbedPane.java
  megamek/src/megamek/client/ui/dialogs/BVDisplayDialog.java
  megamek/src/megamek/client/ui/dialogs/CostDisplayDialog.java
  megamek/src/megamek/client/ui/dialogs/EntityReadoutDialog.java
  megamek/src/megamek/client/ui/panels/AbstractIconChooser.java
  megamek/src/megamek/client/ui/preferences/JComboBoxPreference.java
  megamek/src/megamek/client/ui/preferences/JDoubleNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JIntNumberSpinnerPreference.java
  megamek/src/megamek/client/ui/preferences/JListPreference.java
  megamek/src/megamek/client/ui/preferences/JSplitPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTabbedPanePreference.java
  megamek/src/megamek/client/ui/preferences/JTablePreference.java
  megamek/src/megamek/client/ui/preferences/JTextFieldPreference.java
  megamek/src/megamek/client/ui/preferences/JToggleButtonPreference.java
  megamek/src/megamek/client/ui/preferences/JWindowPreference.java
  megamek/src/megamek/client/ui/preferences/PreferenceElement.java
  megamek/src/megamek/client/ui/preferences/PreferencesNode.java
  megamek/src/megamek/client/ui/preferences/SuitePreferences.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/ReplacePlayersDialog.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerSettingsDialog.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinSpecEditor.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinSpecPanel.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EquipmentMode.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/FighterSquadron.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/MovePath.java
  megamek/src/megamek/common/WeaponOrderHandler.java
  megamek/src/megamek/common/commandline/AbstractCommandLineParser.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKFixedWingSupportFile.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectHomingHandler.java
  megamek/src/megamek/common/weapons/CapitalMissileBearingsOnlyHandler.java
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/Server.java
Labels: Bug

#3686 Fixing Resource Leaks in Server::registerWithServerBrowser
  megamek/src/megamek/server/Server.java
Labels: Bug

#3707 Fixing MM's Try With Resources Resource Leaks
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/generator/RandomCallsignGenerator.java
  megamek/src/megamek/client/generator/RandomUnitGenerator.java
  megamek/src/megamek/client/ui/preferences/SuitePreferences.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/widget/SkinXMLHandler.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/MechFileParser.java
  megamek/src/megamek/common/MechSummaryCache.java
  megamek/src/megamek/common/QuirksHandler.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/common/loaders/MtfFile.java
  megamek/src/megamek/common/util/fileUtils/ImageFileFactory.java
  megamek/src/megamek/server/ScenarioLoader.java
  megamek/src/megamek/utilities/CreateImageAtlases.java
  megamek/src/megamek/utilities/MechCacheCSVTool.java
Labels: Bug

#3713 Fixes #3699 Deadfire LRMs and SRMs have incorrect range brackets
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/WeaponType.java
Labels: Bug, Data

#3735 MHQ 2901: Removing IS Factions from Lupus Generation for 2860-3000
  megamek/data/forcegenerator/2860.xml
  megamek/data/forcegenerator/2865.xml
  megamek/data/forcegenerator/2870.xml
  megamek/data/forcegenerator/2900.xml
  megamek/data/forcegenerator/2950.xml
  megamek/data/forcegenerator/3000.xml
Labels: Bug, Data

#3734 Fixing Nowhwere Typos
  megamek/src/megamek/common/weapons/ArtilleryBayWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/ArtilleryCannonWeaponHandler.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/BombAttackHandler.java
  megamek/src/megamek/common/weapons/MekMortarAirburstHandler.java
  megamek/src/megamek/common/weapons/MekMortarFlareHandler.java
  megamek/src/megamek/common/weapons/MekMortarSmokeHandler.java
  megamek/src/megamek/common/weapons/MissileMineClearanceHandler.java
Labels: Bug
