Repository MegaMek/megamek, pull requests merged in 2022-03, with the labels that each got.

#3480 Correct Remote Sensor Dispenser BA ammo amount
  megamek/src/megamek/common/Mounted.java
Labels: Data

#3488 AbstractDialog: Making FitAndCenter Protected Instead of Private
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
Labels: Refactoring

#3506 3502: Disable Jump Button when prone
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/common/Entity.java
Labels: Bug

#3522 Fixing some repeated typos
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/trees/CamoChooserTree.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/Bay.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/options/IBasicOptionGroup.java
  megamek/src/megamek/common/verifier/TestAero.java
  megamek/src/megamek/server/Server.java
Labels: Bug, Refactoring

#3523 Fixing two useless spaces (found while handling the NLS and i18n comments)
  megamek/src/megamek/common/Entity.java
Labels: Refactoring

#3515 Log4j2: Migrating a bunch of Legacy Logging
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/TestBot.java
  megamek/src/megamek/client/commands/ClientCommand.java
  megamek/src/megamek/client/commands/ShowEntityCommand.java
  megamek/src/megamek/client/generator/RandomUnitGenerator.java
  megamek/src/megamek/client/ratgenerator/ForceNode.java
  megamek/src/megamek/client/ui/swing/ChatterBox2.java
  megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
  megamek/src/megamek/client/ui/swing/ForceGeneratorOptionsView.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/client/ui/swing/MiniMap.java
  megamek/src/megamek/client/ui/swing/RandomMapDialog.java
  megamek/src/megamek/client/ui/swing/ResizeMapDialog.java
  megamek/src/megamek/client/ui/swing/Ruler.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/MapPreviewButton.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/widget/MegamekBorder.java
  megamek/src/megamek/client/ui/swing/widget/SkinXMLHandler.java
  megamek/src/megamek/common/EjectedCrew.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/IBomber.java
  megamek/src/megamek/common/Infantry.java
  megamek/src/megamek/common/MMRandom.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/MechFileParser.java
  megamek/src/megamek/common/Protomech.java
  megamek/src/megamek/common/QuadMech.java
  megamek/src/megamek/common/TripodMech.java
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/templates/TROView.java
  megamek/src/megamek/common/util/ImageUtil.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/ServerLobbyHelper.java
  megamek/src/megamek/server/commands/KickCommand.java
  megamek/src/megamek/server/commands/ListEntitiesCommand.java
  megamek/src/megamek/server/commands/RulerCommand.java
  megamek/src/megamek/server/commands/SeeAllCommand.java
  megamek/src/megamek/server/commands/ShowEntityCommand.java
  megamek/src/megamek/server/commands/ShowValidTargetsCommand.java
  megamek/src/megamek/test/ScenarioLoaderTest.java
  megamek/src/megamek/utils/MegaMekXmlUtil.java
Labels: Enhancement, Refactoring
