Repository MegaMek/megamek, pull requests merged in 2022-05, with the labels that each got.

#3605 MHQ 3167: Fixing Board Utilities Exception on Scenario Start
  megamek/src/megamek/common/util/BoardUtilities.java
Labels: Blocker

#3614 Fixing Athmosphere typos
  megamek/src/megamek/common/pathfinder/LongestPathFinder.java
Labels: Bug, Refactoring

#3608 3607: Fixing Null Swarming Entity Unit ToolTip NPE
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
Labels: Bug, Blocker

#3610 3607: Prevent Entities from Fleeing While Swarming a Unit
  megamek/src/megamek/common/Entity.java
Labels: Bug, Blocker

#3606 Logging Modernization: Updating a Bunch More System.out, System.err, and printStackTraces
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/CEntity.java
  megamek/src/megamek/client/bot/GAAttack.java
  megamek/src/megamek/client/bot/GALance.java
  megamek/src/megamek/client/bot/TestBot.java
  megamek/src/megamek/client/bot/princess/BotGeometry.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/RandomMapPanelAdvanced.java
  megamek/src/megamek/client/ui/swing/RandomMapPanelBasic.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/widget/MechPanelTabStrip.java
  megamek/src/megamek/client/ui/swing/widget/MegamekButton.java
  megamek/src/megamek/client/ui/swing/widget/SkinXMLHandler.java
  megamek/src/megamek/common/EjectedCrew.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/GameReports.java
  megamek/src/megamek/common/KeyBindParser.java
  megamek/src/megamek/common/MMRoll.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/Mounted.java
  megamek/src/megamek/common/MovePath.java
  megamek/src/megamek/common/Protomech.java
  megamek/src/megamek/common/Report.java
  megamek/src/megamek/common/UnitRole.java
  megamek/src/megamek/common/WeaponOrderHandler.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineFlag.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/common/loaders/BLKMechFile.java
  megamek/src/megamek/common/loaders/HmpFile.java
  megamek/src/megamek/common/loaders/HmvFile.java
  megamek/src/megamek/common/loaders/MtfFile.java
  megamek/src/megamek/common/pathfinder/LongestPathFinder.java
  megamek/src/megamek/common/util/BuildingBlock.java
  megamek/src/megamek/common/weapons/ArtilleryBayWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/ArtilleryCannonWeaponHandler.java
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java
  megamek/src/megamek/common/weapons/CapitalMissileBearingsOnlyHandler.java
  megamek/src/megamek/common/weapons/MekMortarAirburstHandler.java
  megamek/src/megamek/common/weapons/MekMortarFlareHandler.java
  megamek/src/megamek/common/weapons/MekMortarSmokeHandler.java
  megamek/src/megamek/common/weapons/MissileMineClearanceHandler.java
  megamek/src/megamek/common/weapons/PopUpMineLauncherHandler.java
  megamek/src/megamek/common/weapons/WeaponHandler.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/test/TestDice.java
Labels: Enhancement, Refactoring, Blocker

#3621 MML 1088: Naval Combat Units can now take Maritime Lifeboats
  megamek/src/megamek/common/verifier/TestTank.java
Labels: Bug

#3633 3630: Properly Cancel MASC Movement on Nag Cancel
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
Labels: Bug, GUI

#3628 TRO View: Fixing Missing Nullable Annotation
  megamek/src/megamek/common/templates/TROView.java
Labels: Bug

#3622 MML 1025: Adding MagLev Engine weights
  megamek/src/megamek/common/Engine.java
Labels: Bug

#3629 Detachable Unit Display Removal
  megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/UnitDetailPane.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/util/UIUtil.java
  megamek/src/megamek/client/ui/swing/widget/DetachablePane.java
Labels: GUI, Blocker

#3635 Suite Options: Adding Options Changed Events
  megamek/src/megamek/MMOptionsChangedEvent.java
  megamek/src/megamek/SuiteOptionsChangedEvent.java
Labels: Enhancement

#3634 Adjust initiative bonus processing
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/Team.java
  megamek/unittests/megamek/common/TeamTest.java
Labels: Bug

#3640 Fixing Attack Action NPE from Missing Nullable Handling
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/actions/AbstractAttackAction.java
Labels: Bug, Blocker

#3642 3641: Fixing Server Game End ConMod
  megamek/src/megamek/server/Server.java
Labels: Bug, Blocker

#3643 Trimming Service IP Address
  megamek/src/megamek/client/ui/swing/gameConnectionDialogs/ConnectDialog.java
Labels: Bug, GUI, Blocker

#3625 Enum All The Things: Separate Entity Enums
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/CEntity.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/LandAirMech.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/MechFileParser.java
  megamek/src/megamek/common/MoveStep.java
  megamek/src/megamek/common/QuadVee.java
  megamek/src/megamek/common/Tank.java
  megamek/src/megamek/common/WeaponOrderHandler.java
  megamek/src/megamek/common/battlevalue/MekBVCalculator.java
  megamek/src/megamek/common/enums/MPBoosters.java
  megamek/src/megamek/common/enums/WeaponSortOrder.java
  megamek/src/megamek/common/verifier/TestEntity.java
  megamek/src/megamek/server/Server.java
Labels: Refactoring

#3650 JUnit 5: Migrating JUnit Tests to JUnit 5
  megamek/build.gradle
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/common/BoardDimensions.java
  megamek/src/megamek/common/Mounted.java
  megamek/unittests/megamek/client/bot/ChatProcessorTest.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsFactoryTest.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsFactoryTestConstants.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsTest.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsTestConstants.java
  megamek/unittests/megamek/client/bot/princess/BotGeometryTest.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
  megamek/unittests/megamek/client/bot/princess/FiringPlanTest.java
  megamek/unittests/megamek/client/bot/princess/NewtonAerospacePathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/PhysicalInfoTest.java
  megamek/unittests/megamek/client/bot/princess/PrincessTest.java
  megamek/unittests/megamek/client/bot/princess/WeaponFireInfoTest.java
  megamek/unittests/megamek/client/generator/RandomUnitGeneratorTest.java
  megamek/unittests/megamek/common/AmmoTypeTest.java
  megamek/unittests/megamek/common/BoardDimensionsTests.java
  megamek/unittests/megamek/common/ComputeECMTest.java
  megamek/unittests/megamek/common/ConfigurationTests.java
  megamek/unittests/megamek/common/CrewTest.java
  megamek/unittests/megamek/common/EntityTest.java
  megamek/unittests/megamek/common/EquipmentTypeLookupTest.java
  megamek/unittests/megamek/common/EquipmentTypeTest.java
  megamek/unittests/megamek/common/GameTest.java
  megamek/unittests/megamek/common/JumpshipTest.java
  megamek/unittests/megamek/common/MapSettingsTest.java
  megamek/unittests/megamek/common/MechFileParserTest.java
  megamek/unittests/megamek/common/MovePathTest.java
  megamek/unittests/megamek/common/PlanetaryConditionsTest.java
  megamek/unittests/megamek/common/PlayerTest.java
  megamek/unittests/megamek/common/TargetRollTest.java
  megamek/unittests/megamek/common/TeamTest.java
  megamek/unittests/megamek/common/UnitNameTrackerTest.java
  megamek/unittests/megamek/common/WeaponTypeTest.java
  megamek/unittests/megamek/common/loaders/BLKFileTest.java
  megamek/unittests/megamek/common/loaders/MtfFileTest.java
  megamek/unittests/megamek/common/loaders/TdbFileTest.java
  megamek/unittests/megamek/common/options/GameOptionsTest.java
  megamek/unittests/megamek/common/preference/PreferenceManagerTest.java
  megamek/unittests/megamek/common/util/AddBotUtilTest.java
  megamek/unittests/megamek/common/util/BoardUtilitiesTest.java
  megamek/unittests/megamek/common/util/weightedMaps/WeightedMapTest.java
  megamek/unittests/megamek/common/verifier/BayDataTest.java
  megamek/unittests/megamek/common/verifier/EntityVerifierTest.java
  megamek/unittests/megamek/common/verifier/TestAdvancedAerospaceTest.java
  megamek/unittests/megamek/common/verifier/TestProtoMekTest.java
  megamek/unittests/megamek/common/verifier/TestSupportVehicleTest.java
  megamek/unittests/megamek/server/victory/ServerTest.java
  megamek/unittests/megamek/server/victory/VictoryResultTest.java
Labels: Tests

#3656 3613: Princess: Adding Stop Swarm Behaviour For Fleeing
  megamek/src/megamek/client/bot/princess/Princess.java
Labels: Enhancement, Princess/AI

#3661 Logging: Removing Outdated Release Date
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/SuiteConstants.java
Labels: Enhancement, Refactoring
