Repository MegaMek/megamek, pull requests merged in 2023-01, with the labels that each got.

#4080 SkillLevel Enum: Expanding Functionality for MHQ Requirements
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: Enhancement, MHQ-origin MM Issues

#4084 Java 17: Manifest File Add-Opens
  megamek/build.gradle
Labels: Blocker, Build / CI

#4096 weapon order
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
Labels: Enhancement, GUI, Unit Display

#4078 unit tool tip updates
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/IBomber.java
  megamek/src/megamek/common/LandAirMech.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/VTOL.java
Labels: Enhancement, GUI, Unit Display

#4100 Base Components: Adding JDisableablePanel
  megamek/src/megamek/client/ui/baseComponents/JDisableablePanel.java
Labels: Enhancement, GUI

#4110 MHQ 3558: Track RATs Using a final HashMap
  megamek/src/megamek/client/generator/RandomUnitGenerator.java
  megamek/unittests/megamek/client/generator/RandomUnitGeneratorTest.java
Labels: Bug

#4108 4082: Removing Static Message Constant Uses
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/dialogs/MiniReportDisplayDialog.java
  megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java
  megamek/src/megamek/client/ui/swing/ChatterBox.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
  megamek/src/megamek/client/ui/swing/PlayerListDialog.java
  megamek/src/megamek/client/ui/swing/RandomMapDialog.java
  megamek/src/megamek/client/ui/swing/ReplacePlayersDialog.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/ResizeMapDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/common/commandline/AbstractCommandLineParser.java
  megamek/src/megamek/common/commandline/ClientServerCommandLineParser.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/server/DedicatedServer.java
Labels: Enhancement, Performance

#4109 4098: Adding Sprite Camouflage and Damage Export Options
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/dialogs/CamoChooserDialog.java
  megamek/src/megamek/client/ui/panels/EntityImagePanel.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java
  megamek/src/megamek/client/ui/swing/lobby/MekForceTreeRenderer.java
  megamek/src/megamek/client/ui/swing/lobby/MekTableModel.java
  megamek/src/megamek/client/ui/swing/tileset/EntityImage.java
  megamek/src/megamek/common/Entity.java
Labels: Enhancement

#4112 BaseComponents: Adding Nag Dialog Setup
  megamek/i18n/megamek/client/bot/messages.properties
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MMConstants.java
  megamek/src/megamek/MMOptions.java
  megamek/src/megamek/client/bot/ui/swing/BotGUI.java
  megamek/src/megamek/client/ui/baseComponents/AbstractNagDialog.java
  megamek/src/megamek/client/ui/dialogs/nagDialogs/BotReadmeNagDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/util/AddBotUtil.java
Labels: Enhancement, GUI

#4092 Lobby updates
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
  megamek/src/megamek/client/ui/swing/UnitEditorDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekCellFormatter.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerTable.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerUnitRoleSorter.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
Labels: Enhancement, GUI

#4097 attack tool tip update
  megamek/src/megamek/client/ui/swing/boardview/AttackSprite.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/common/Coords.java
Labels: Enhancement, GUI

#4130 show movement for all entity types on unit tool tip
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/LandAirMech.java
Labels: Bug, Enhancement, GUI

#4132 tripod fixes
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/Entity.java
Labels: Bug, GUI

#4121 LocalParser: Tearing Out Unused Code
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/util/LocaleParser.java
Labels: Refactoring

#4120 Options Constants: Accessibility Cleanup
  megamek/src/megamek/common/options/OptionsConstants.java
Labels: Accessibility, Refactoring

#4125 button tool tip for hot keys
  megamek/i18n/megamek/client/messages.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/AbstractPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/DeployMinefieldDisplay.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/KeyBindingsOverlay.java
  megamek/src/megamek/client/ui/swing/boardview/PlanetaryConditionsOverlay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
Labels: Bug, Enhancement, GUI
