Repository MegaMek/megamek, pull requests merged in 2023-07, with the labels that each got.

#4600 In Lounge, Load from MUL will not increment deployment round
  megamek/src/megamek/client/ui/swing/ClientGUI.java
Labels: Bug

#4590 Base Components: Enforce Title For Accessibility
  megamek/src/megamek/client/ui/baseComponents/AbstractDialog.java
Labels: Bug, GUI

#4576 Gamemaster mode can edit unit during game
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CustomMechDialog.java
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
Labels: Enhancement

#4631 Alpha Strike Stats Table is now sortable
  megamek/src/megamek/client/ui/dialogs/ASStatsDialog.java
  megamek/src/megamek/client/ui/swing/ASStatsTablePanel.java
Labels: Enhancement

#4605 ReplacePlayerDialog can now edit existing bot configs
  megamek/docs/Bot Stuff/Princess Notes.txt
  megamek/docs/help/en/PrincessBotDocumentation.html
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_de.properties
  megamek/i18n/megamek/client/messages_es.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/EditBotsDialog.java
  megamek/src/megamek/client/ui/swing/ForceGeneratorViewUi.java
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
  megamek/src/megamek/client/ui/swing/RandomNameDialog.java
  megamek/src/megamek/client/ui/swing/ReplacePlayersDialog.java
  megamek/src/megamek/client/ui/swing/SkillGenerationDialog.java
  megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerTable.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerTablePopup.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/MekTreeTopLevelSorter.java
  megamek/src/megamek/common/util/AddBotUtil.java
Labels: Enhancement, GUI

#4624 CodeUtilities: Add Unit Testing
  megamek/src/megamek/codeUtilities/MathUtility.java
  megamek/src/megamek/codeUtilities/ObjectUtility.java
  megamek/src/megamek/codeUtilities/StringUtility.java
  megamek/unittests/megamek/codeUItilities/MathUtilityTest.java
  megamek/unittests/megamek/codeUItilities/ObjectUtilityTest.java
  megamek/unittests/megamek/codeUItilities/StringUtilityTest.java
Labels: Bug, Tests
