Repository MegaMek/megamek, pull requests merged in 2023-09, with the labels that each got.

#4766 RATGeneratorEditor: Show unit type instead of number
  megamek/src/megamek/utilities/RATGeneratorEditor.java
Labels: RAT Editor

#4763 Quirks: VTOL Rotor Arrangement Co-Axial/Dual Rotor
  megamek/data/canonUnitQuirks.xml
  megamek/data/mechfiles/vehicles/XTRs/Most Wanted/Hawk Moth Verwandlung.blk
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/common/options/Quirks.java
Labels: Bug, Enhancement

#4761 correct NPE in bvReports when player is not on a team
  megamek/src/megamek/server/GameManager.java
Labels: Bug
