Repository MegaMek/megamek, pull requests merged in 2023-08, with the labels that each got.

#4673 Clan TAG: Remove "(Clan)" from name
  megamek/src/megamek/common/weapons/tag/CLTAG.java
Labels: For New Dev Cycle

#4684 add option for GM control over done in report phases
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/server/GameManager.java
Labels: Enhancement, GUI, GM Tools

#4736 Nine vehicle .blks had duplicate tonnage tags
  megamek/data/mechfiles/vehicles/3039u/Axel Heavy Tank Mk 2.blk
  megamek/data/mechfiles/vehicles/3039u/Ontos Heavy Tank (Fusion).blk
  megamek/data/mechfiles/vehicles/3039u/Ontos Heavy Tank (LRM).blk
  megamek/data/mechfiles/vehicles/3039u/Rommel Tank.blk
  megamek/data/mechfiles/vehicles/3058Uu/Axel Heavy Tank IIC (XL).blk
  megamek/data/mechfiles/vehicles/3058Uu/Axel Heavy Tank IIC.blk
  megamek/data/mechfiles/vehicles/ProtoTypes/Rommel Tank (Howitzer) Production.blk
  megamek/data/mechfiles/vehicles/XTRs/Periphery/Patton Tank SB.blk
  megamek/data/mechfiles/vehicles/XTRs/Steiner/Rommel Tank (Howitzer) Prototype.blk
Labels: Data
