Repository MegaMek/megamek, pull requests merged in 2023-05, with the labels that each got.

#4362 detailed unit counts
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/server/GameManager.java
Labels: Enhancement, Reports

#4379 calculate heat over using modified heat sink value
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/common/Entity.java
Labels: Bug

#4288 Optional "Ignore Nag" button to allow ready() call even if getNagForNoAction is enabled
  .gitignore
  megamek/i18n/megamek/client/messages.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/AbstractPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/ActionPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/AttackPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/DeployMinefieldDisplay.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/KeyBindingsOverlay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
Labels: Enhancement, GUI

#4435 Data: Add two missing unit roles and remove one redundant quirks entry
  megamek/data/canonUnitQuirks.xml
  megamek/data/unit_roles.txt
Labels: Data

#4436 Additional updates for name_changes.txt for (Standard) removal
  megamek/data/mechfiles/name_changes.txt
Labels: Data

#4432 fix issue with seen by client setting unit tool tip index mismatch
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
Labels: Bug

#4446 show teams before players on bv count report section
  megamek/src/megamek/server/GameManager.java
Labels: Enhancement, Reports

#4430 highlight min - max visual and sensor ranges
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_es.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/i18n/megamek/common/messages_es.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/FieldofFireSprite.java
  megamek/src/megamek/client/ui/swing/boardview/SensorRangeSprite.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/ExtraPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
  megamek/src/megamek/client/ui/swing/widget/GeneralInfoMapSet.java
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/Entity.java
Labels: Enhancement, GUI

#4450 when tacops sensors is not on, dont show sensor rings
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
Labels: Bug

#4451 when tacops sensors is not on, show visual range in tool tip
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/PlanetaryConditions.java
Labels: Bug, GUI

#4443 Code maintenance
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/FighterSquadron.java
  megamek/src/megamek/common/GunEmplacement.java
  megamek/src/megamek/common/LargeSupportTank.java
  megamek/src/megamek/common/SuperHeavyTank.java
  megamek/src/megamek/common/SupportTank.java
  megamek/src/megamek/common/SupportVTOL.java
  megamek/src/megamek/common/TeleMissile.java
Labels: For New Dev Cycle

#4433 Map setups (continued)
  megamek/src/megamek/client/ui/swing/RandomMapDialog.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/MapSettings.java
  megamek/src/megamek/common/MapSetup.java
  megamek/src/megamek/common/Terrains.java
  megamek/src/megamek/server/ServerBoardHelper.java
Labels: For New Dev Cycle

#4454 in end report show active units with data from their unit tool tip
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/server/GameManager.java
Labels: Reports
