Repository MegaMek/megamek, pull requests merged in 2023-12, with the labels that each got.

#4928 dont set gm to an observer when they have no units
  megamek/src/megamek/server/GameManager.java
Labels: Bug, GM Tools

#4932 add illumination indicator to the hextooltip and unittooltip
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/tooltip/HexTooltip.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/enums/IlluminationLevel.java
  megamek/src/megamek/common/util/SerializationHelper.java
Labels: Unit Display

#4953 null check for ghostTargetRoll
  megamek/src/megamek/common/Entity.java
Labels: Bug

#4921 add client settings for unit tooltip bg colors
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/boardview/AttackSprite.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/lobby/MekTableModel.java
  megamek/src/megamek/client/ui/swing/tooltip/HexTooltip.java
  megamek/src/megamek/client/ui/swing/tooltip/PilotToolTip.java
  megamek/src/megamek/client/ui/swing/tooltip/TipUtil.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/SummaryPanel.java
Labels: Unit Display

#4955 MechSummaryCache BV calculation: ignore pilot skill to ignore saved a…
  megamek/src/megamek/common/MechSummaryCache.java
Labels: CGL Request

#4964 cleanup piloting rolls report
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/server/GameManager.java
Labels: Reports

#4963 show heat effects after unit in heat report
  megamek/src/megamek/server/GameManager.java
Labels: Reports

#4957 more tooltips colors
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/AimedShotDialog.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/EntityChoiceDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/TargetChoiceDialog.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/lobby/MekTableModel.java
  megamek/src/megamek/client/ui/swing/tooltip/HexTooltip.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/SummaryPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/common/enums/IlluminationLevel.java
Labels: Unit Display

#4922 add deployment options
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CustomMechDialog.java
  megamek/src/megamek/client/ui/swing/Ruler.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekCellFormatter.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyUtility.java
  megamek/src/megamek/client/ui/swing/lobby/MekTableModel.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerSettingsDialog.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerTable.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EntityListFile.java
  megamek/src/megamek/common/MULParser.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/Server.java
Labels: GUI, GM Tools

#4981 add unit readout button that displays the unit summary, tro, and as card
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/client/ui/swing/unitDisplay/ExtraPanel.java
Labels: Unit Display

#4980 allow gm to configure spas in game
  megamek/src/megamek/client/ui/swing/MapMenu.java
Labels: GM Tools
