Repository MegaMek/megamek, pull requests merged in 2024-04, with the labels that each got.

#5289 Improved MissionRole Switch Cases & Role List
  megamek/docs/RAT Stuff/rat-generator.txt
  megamek/src/megamek/client/ratgenerator/MissionRole.java
Labels: Refactoring

#5291 Industrial tripod cockpit
  megamek/i18n/megamek/common/equipmentmessages.properties
  megamek/src/megamek/client/bot/princess/FireControl.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/actions/WeaponAttackAction.java
  megamek/src/megamek/common/alphaStrike/conversion/ASMekSpecialAbilityConverter.java
  megamek/src/megamek/common/battlevalue/MekBVCalculator.java
  megamek/src/megamek/common/cost/MekCostCalculator.java
  megamek/src/megamek/common/verifier/TestMech.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
Labels: Bug

#5303 add client settings for report colors
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/report-messages.properties
  megamek/i18n/megamek/common/report-messages_es.properties
  megamek/i18n/megamek/common/report-messages_ru.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
  megamek/src/megamek/common/Report.java
Labels: Reports, For New Dev Cycle

#5367 correct issue when using multiple boards and restricting deployment a…
  megamek/src/megamek/client/ui/swing/CustomMechDialog.java
Labels: Bug

#5295 add light conditions glare and solar flare
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/LandAirMech.java
  megamek/src/megamek/common/MoveStep.java
  megamek/src/megamek/common/actions/AbstractAttackAction.java
  megamek/src/megamek/common/actions/WeaponAttackAction.java
  megamek/src/megamek/common/planetaryconditions/Light.java
  megamek/src/megamek/common/planetaryconditions/PlanetaryConditions.java
  megamek/src/megamek/server/GameManager.java
Labels: (RFE) Enhancement, For New Dev Cycle, Planetary Conditions

#5301 Flight path indicator
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/FlightPathIndicatorSprite.java
  megamek/src/megamek/client/ui/swing/boardview/StepSprite.java
Labels: For New Dev Cycle

#5327 Code cleanup for string drawing
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovementModifierEnvelopeSprite.java
  megamek/src/megamek/client/ui/swing/boardview/TextMarkerSprite.java
  megamek/src/megamek/client/ui/swing/util/FontHandler.java
Labels: For New Dev Cycle

#5321 add client settings for report font
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
  megamek/src/megamek/common/Report.java
Labels: Reports, For New Dev Cycle

#5334 Fix for request 5333 - Add Gunnery / Pilot BV values to the unit selection screen.
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/dialog/AbstractUnitSelectorDialog.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: For New Dev Cycle

#5308 Remove superclass JPanel from BoardView
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ChatterBox2.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/OffBoardTargetOverlay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/AbstractBoardViewOverlay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/BoardViewPanel.java
  megamek/src/megamek/client/ui/swing/boardview/CursorSprite.java
  megamek/src/megamek/client/ui/swing/boardview/EntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/GhostEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricSprite.java
  megamek/src/megamek/client/ui/swing/boardview/IsometricWreckSprite.java
  megamek/src/megamek/client/ui/swing/boardview/MovingEntitySprite.java
  megamek/src/megamek/client/ui/swing/boardview/Sprite.java
  megamek/src/megamek/client/ui/swing/boardview/StepSprite.java
  megamek/src/megamek/client/ui/swing/boardview/WreckSprite.java
  megamek/src/megamek/client/ui/swing/skinEditor/SkinEditorMainGUI.java
  megamek/src/megamek/client/ui/swing/tileset/TilesetManager.java
Labels: For New Dev Cycle

#5336 Keydispatcher aka MegaMekController simplification
  megamek/src/megamek/client/ui/swing/AbstractPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/ActionPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/ChatterBox2.java
  megamek/src/megamek/client/ui/swing/FiringDisplay.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/PointblankShotDisplay.java
  megamek/src/megamek/client/ui/swing/PrephaseDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/util/CommandAction.java
  megamek/src/megamek/client/ui/swing/util/KeyBindReceiver.java
  megamek/src/megamek/client/ui/swing/util/MegaMekController.java
Labels: For New Dev Cycle

#5318 Boardview: Extract Shadowmap
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/TerrainShadowHelper.java
  megamek/src/megamek/client/ui/swing/tileset/EntityImage.java
  megamek/src/megamek/common/util/ImageUtil.java
Labels: For New Dev Cycle

#5369 Add actionlistener for combobox in DialogOptionComponent
  megamek/src/megamek/client/ui/swing/CustomMechDialog.java
  megamek/src/megamek/client/ui/swing/DialogOptionComponent.java
  megamek/src/megamek/client/ui/swing/DialogOptionListener.java
  megamek/src/megamek/client/ui/swing/GameOptionsDialog.java
Labels: For New Dev Cycle

#5340 RFE 5284: add alt munition outfitting for princess
  megamek/docs/equipment.txt
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MMConstants.java
  megamek/src/megamek/client/generator/TeamLoadoutGenerator.java
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerSettingsDialog.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/ITechnology.java
  megamek/src/megamek/common/Team.java
  megamek/src/megamek/common/containers/MunitionTree.java
  megamek/unittests/megamek/client/generator/MunitionTreeTest.java
  megamek/unittests/megamek/client/generator/TeamLoadoutGeneratorTest.java
Labels: Princess/AI, In Development (Draft)

#5380 Update mechset reading and icon tests
  megamek/src/megamek/client/ui/swing/tileset/GenerateGenericIconList.java
  megamek/src/megamek/client/ui/swing/tileset/IconTest.java
  megamek/src/megamek/client/ui/swing/tileset/MechSetTest.java
  megamek/src/megamek/client/ui/swing/tileset/MechTileset.java
  megamek/src/megamek/common/util/fileUtils/StandardTextfileStreamTokenizer.java
  megamek/src/megamek/utilities/MechSetTest.java
Labels: For New Dev Cycle
