Repository MegaMek/megamek, pull requests merged in 2024-06, with the labels that each got.

#5531 Allow Harjel on support vehicles
  megamek/src/megamek/common/MiscType.java
Labels: Support Vehicles

#5527 RATGen/force generator role handling updates
  megamek/docs/RAT Stuff/rat-generator.txt
  megamek/src/megamek/client/ratgenerator/MissionRole.java
Labels: Data, Create Random Army Issue

#5546 Tooltip updates for role additions
  megamek/i18n/megamek/client/messages.properties
Labels: Data

#5550 Set Default Edge States to True
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/common/options/PilotOptions.java
Labels: (RFE) Enhancement

#5551 Update Shogun C 2.mtf
  megamek/data/mechfiles/mechs/3145/NTNU RS/NTNU/Shogun C 2.mtf
Labels: Data

#5560 Changed Show Report Sprites in Report Log Default State to False
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
Labels: GUI, Reports

#5562 Filtered SPA display to Not Include Edge Uses
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekCellFormatter.java
Labels: GUI

#5586 Updated Game Options and Report Log Default Preferences
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/common/options/GameOptions.java
Labels: Bug, GUI, Reports

#5623 adjust wind direction order
  megamek/src/megamek/common/planetaryconditions/WindDirection.java
Labels: Bug, Planetary Conditions

#5652 Fix ammo carrier issue that prevents Princess from firing ammo-based weapons
  megamek/src/megamek/common/actions/WeaponAttackAction.java
Labels: Bug

#5570 ScenarioV2 extension, sky map
  megamek/data/images/hexes/atmospheric_map/sky.png
  megamek/data/images/hexes/hq_saxarba.tileset
  megamek/data/images/hexes/saxarba.tileset
  megamek/data/scenarios/Examples/ExampleV2.mms
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/scenario/ScenarioChooser.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/MechSummary.java
  megamek/src/megamek/common/Terrains.java
  megamek/src/megamek/common/icons/Camouflage.java
  megamek/src/megamek/common/icons/Portrait.java
  megamek/src/megamek/common/jacksonadapters/BoardDeserializer.java
  megamek/src/megamek/common/jacksonadapters/CrewDeserializer.java
  megamek/src/megamek/common/jacksonadapters/EntityDeserializer.java
  megamek/src/megamek/common/jacksonadapters/MMUReader.java
  megamek/src/megamek/common/scenario/ScenarioV2.java
  megamek/src/megamek/common/util/BoardUtilities.java
Labels: For New Dev Cycle
