Repository MegaMek/megamek, pull requests merged in 2024-01, with the labels that each got.

#5008 Fix Elemental III Date
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [AP Gauss](Sqd4).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [AP Gauss](Sqd5).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [AP Gauss](Sqd6).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [Flamer] (Sqd4).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [Flamer] (Sqd5).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [Flamer] (Sqd6).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [MicroPL] (Sqd4).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [MicroPL] (Sqd5).blk
  megamek/data/mechfiles/battlearmor/Rec Guides ilClan/Vol 24/Elemental III BA [MicroPL] (Sqd6).blk
Labels: Data

#4994 Weapon sorting (for MML)
  megamek/src/megamek/common/weapons/artillery/LongTomCannon.java
  megamek/src/megamek/common/weapons/artillery/SniperCannon.java
  megamek/src/megamek/common/weapons/artillery/ThumperCannon.java
  megamek/src/megamek/common/weapons/flamers/ISVehicleFlamer.java
  megamek/src/megamek/common/weapons/gaussrifles/CLAPGaussRifle.java
  megamek/src/megamek/common/weapons/lasers/CLImprovedLaserLarge.java
  megamek/src/megamek/common/weapons/lasers/CLImprovedPulseLaserLarge.java
  megamek/src/megamek/common/weapons/lasers/ISERLaserLarge.java
  megamek/src/megamek/common/weapons/lasers/ISERLaserMedium.java
  megamek/src/megamek/common/weapons/lasers/ISERLaserSmall.java
  megamek/src/megamek/common/weapons/lasers/ISLaserLarge.java
  megamek/src/megamek/common/weapons/lasers/ISLaserMedium.java
  megamek/src/megamek/common/weapons/lasers/ISLaserSmall.java
  megamek/src/megamek/common/weapons/ppc/CLERPPC.java
  megamek/src/megamek/common/weapons/ppc/ISERPPC.java
  megamek/src/megamek/common/weapons/ppc/ISKinsSlaughterPPC.java
  megamek/src/megamek/common/weapons/ppc/ISSnubNosePPC.java
Labels: Data

#5023 correct conversion exception causing search to not work
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
Labels: Bug, Reports

#5042 correct issue with life support abbreviation in unit tooltip
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
Labels: Bug

#4985 add in game force display dialog
  megamek/i18n/megamek/client/messages.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/ReportDisplay.java
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayDialog.java
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayMekCellFormatter.java
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayMekTreeModel.java
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayMekTreeRenderer.java
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayPanel.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekCellFormatter.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
Labels: (RFE) Enhancement, GUI

#5059 unit tooltip pilot updates
  megamek/src/megamek/client/ui/swing/tooltip/PilotToolTip.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
Labels: Unit Display

#5041 Princess Ice & Infantry On Ice Fix
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
Labels: Princess/AI

#5057 lobby force updates
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java
  megamek/src/megamek/client/ui/swing/lobby/MekTreeForceModel.java
Labels: GUI

#5071 MUL parser updates
  megamek/src/megamek/common/EntityListFile.java
  megamek/src/megamek/common/MULParser.java
Labels: Refactoring

#5091 move toInt into StringUtil
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java
  megamek/src/megamek/common/MechSearchFilter.java
  megamek/src/megamek/common/util/StringUtil.java
Labels: Refactoring
