Repository MegaMek/megamek, pull requests merged in 2024-11, with the labels that each got.

#6180 Fix/blkfile parser encoding
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/util/BuildingBlock.java
  megamek/unittests/megamek/common/verifier/TestSupportVehicleTest.java
Labels: Bug

#6182 Fix loading of old resizable equipment
  megamek/src/megamek/common/loaders/BLKAeroSpaceFighterFile.java
  megamek/src/megamek/common/loaders/BLKBattleArmorFile.java
  megamek/src/megamek/common/loaders/BLKConvFighterFile.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKFixedWingSupportFile.java
  megamek/src/megamek/common/loaders/BLKSmallCraftFile.java
  megamek/src/megamek/common/loaders/BLKWarshipFile.java
  megamek/src/megamek/common/loaders/MtfFile.java
Labels: Bug

#6185 [RFE] Teach Princess to not always unjam RAC's immediately #6052
  megamek/src/megamek/client/bot/princess/Princess.java
Labels: Bug

#6186 Allow pausing a Princess-only game
  megamek/i18n/megamek/client/messages.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/AbstractClient.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
  megamek/src/megamek/common/net/enums/PacketCommand.java
  megamek/src/megamek/server/Server.java
Labels: (RFE) Enhancement

#6190 Allow printing unit list from MM
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: (RFE) Enhancement

#6196 add an advanced search for boards to the lobby
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/advancedSearchMap/AdvancedSearchMapDialog.java
  megamek/src/megamek/client/ui/advancedSearchMap/BoardTableModel.java
  megamek/src/megamek/client/ui/advancedsearch/MekSearchFilter.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/util/StringUtil.java
  megamek/src/megamek/utilities/BoardClassifier.java
Labels: GUI, Map and Board

#6203 find duplicate boards
  megamek/src/megamek/utilities/BoardsTagger.java
Labels: Data

#6222 feat: adds the players team in the BV report
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Reports

#6223 feat: Allows GM to control any bot in the game
  megamek/src/megamek/client/ui/swing/MapMenu.java
Labels: GUI, GM Tools

#6216 add additional board auto tags
  megamek/src/megamek/utilities/BoardsTagger.java
Labels: Map and Board
