Repository MegaMek/megamek, pull requests merged in 2024-07, with the labels that each got.

#5731 Fix incorrect onGround usage and make sure ASF bombs are always cleared before refitting
  megamek/src/megamek/client/generator/TeamLoadoutGenerator.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java
  megamek/src/megamek/client/ui/swing/lobby/PlayerSettingsDialog.java
Labels: Aerospace

#5780 Add Word Wrap Function to WrapLayout and Integrated it into TROView
  megamek/src/megamek/client/ui/WrapLayout.java
  megamek/src/megamek/common/templates/TROView.java
Labels: Bug, GUI, MHQ-origin MM Issues

#5810 Data, spelling, typos
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA David (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA David (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA David (Sqd6).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Interdictor (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Interdictor (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Interdictor (Sqd6).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MG (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MG (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MG (Sqd6).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MRM (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MRM (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA MRM (Sqd6).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Pop Up Mine (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Pop Up Mine (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA Pop Up Mine (Sqd6).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA SRM (Sqd4).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA SRM (Sqd5).blk
  megamek/data/mechfiles/battlearmor/3145/Liao/Shen Long BA SRM (Sqd6).blk
  megamek/data/mechfiles/fighters/TRO3085u/Cutting Edge/Wusun Prime.blk
  megamek/data/mechfiles/fighters/TRO3145/NTNU/Morgenstern MR-1SE.blk
  megamek/data/mechfiles/mechs/3060u/Beowulf BEO-12.mtf
  megamek/data/mechfiles/mechs/3060u/Helios HEL-3D.mtf
  megamek/data/mechfiles/mechs/3067/Arcas.mtf
  megamek/data/mechfiles/mechs/3085u/Cutting Edge/Karhu Prime.mtf
  megamek/data/mechfiles/mechs/3085u/Cutting Edge/Kuma.mtf
  megamek/data/mechfiles/mechs/3085u/Cutting Edge/Onager.mtf
  megamek/data/mechfiles/mechs/3085u/Cutting Edge/Shadow Cat II.mtf
  megamek/data/mechfiles/mechs/3145/Clans/Vulture (Mad Dog) Mk III (Prime).mtf
  megamek/data/mechfiles/mechs/3145/Davion/Gunsmith CH11-NG.mtf
  megamek/data/mechfiles/mechs/3145/NTNU RS/Templar TLR1-OR.mtf
  megamek/data/mechfiles/mechs/3145/Republic/Kheper KHP-7R.mtf
  megamek/data/mechfiles/mechs/3145/Steiner/Ursa URA-2A.mtf
  megamek/data/mechfiles/mechs/WoR Supplemental/Pariah (Septicemia) US.mtf
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/i18n/megamek/common/options/messages.properties
  megamek/i18n/megamek/common/report-messages.properties
Labels: Data
