Repository MegaMek/megamek, pull requests merged in 2024-02, with the labels that each got.

#5121 bot command updates
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/ChatCommands.java
  megamek/src/megamek/client/commands/BotHelpCommand.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/commands/BotHelpCommand.java
Labels: GM Tools

#5126 turn timer updates
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/options/messages.properties
  megamek/mmconf/defaultKeyBinds.xml
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/DeployMinefieldDisplay.java
  megamek/src/megamek/client/ui/swing/PhysicalDisplay.java
  megamek/src/megamek/client/ui/swing/SelectArtyAutoHitHexDisplay.java
  megamek/src/megamek/client/ui/swing/StatusBarPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/TargetingPhaseDisplay.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
  megamek/src/megamek/client/ui/swing/util/TurnTimer.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
Labels: GUI

#5136 switch to using name : code maps for advanced search combo box loads
  megamek/src/megamek/client/ui/swing/unitSelector/TWAdvancedSearchPanel.java
  megamek/src/megamek/common/Engine.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/MechSearchFilter.java
  megamek/src/megamek/common/MechSummary.java
  megamek/src/megamek/common/MechSummaryCache.java
  megamek/src/megamek/common/SimpleTechLevel.java
  megamek/src/megamek/common/equipment/ArmorType.java
Labels: Bug, Advanced Search

#5147 fix weather restrictions wind
  megamek/src/megamek/common/WeatherRestriction.java
Labels: Bug

#5165 Reduce connections between Player/Team and Game/Entity
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/princess/Precognition.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/InGameObject.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/Team.java
  megamek/src/megamek/server/GameManager.java
  megamek/src/megamek/server/ServerReportsHelper.java
  megamek/unittests/megamek/server/victory/GameManagerTest.java
Labels: For New Dev Cycle

#5166 Adding Clan Personnel Tracking to MegaMek
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_de.properties
  megamek/src/megamek/client/bot/MoveOption.java
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/generator/RandomNameGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/AbstractSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ConstantSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ModifiedConstantSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/ModifiedTotalWarfareSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/TaharqaSkillGenerator.java
  megamek/src/megamek/client/generator/skillGenerators/TotalWarfareSkillGenerator.java
  megamek/src/megamek/client/ratgenerator/CrewDescriptor.java
  megamek/src/megamek/client/ui/swing/CustomMechDialog.java
  megamek/src/megamek/client/ui/swing/CustomPilotView.java
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
  megamek/src/megamek/client/ui/swing/RandomNameDialog.java
  megamek/src/megamek/client/ui/swing/dialog/MegaMekUnitSelectorDialog.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/common/Crew.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/LAMPilot.java
  megamek/src/megamek/common/MULParser.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/actions/FindClubAction.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/server/ScenarioLoader.java
Labels: For New Dev Cycle

#5156 Embed Fluff Images in the Unit Files (MM part)
  megamek/src/megamek/client/ui/Base64Image.java
  megamek/src/megamek/client/ui/swing/util/FluffImageHelper.java
  megamek/src/megamek/common/BTObject.java
  megamek/src/megamek/common/BuildingTarget.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EntityFluff.java
  megamek/src/megamek/common/HexTarget.java
  megamek/src/megamek/common/INarcPod.java
  megamek/src/megamek/common/Jumpship.java
  megamek/src/megamek/common/Mech.java
  megamek/src/megamek/common/MechSummary.java
  megamek/src/megamek/common/MechSummaryCache.java
  megamek/src/megamek/common/MinefieldTarget.java
  megamek/src/megamek/common/SpaceStation.java
  megamek/src/megamek/common/Warship.java
  megamek/src/megamek/common/alphaStrike/ASCardDisplayable.java
  megamek/src/megamek/common/alphaStrike/AlphaStrikeElement.java
  megamek/src/megamek/common/alphaStrike/cardDrawer/ASCard.java
  megamek/src/megamek/common/alphaStrike/conversion/ASConverter.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKWarshipFile.java
  megamek/src/megamek/common/loaders/MtfFile.java
  megamek/src/megamek/common/strategicBattleSystems/SBFFormation.java
  megamek/src/megamek/common/util/ImageUtil.java
Labels: For New Dev Cycle
