Repository MegaMek/megamek, pull requests merged in 2024-10, with the labels that each got.

#6053 Enhance `wordWrap` with HTML Tags for Line Breaks
  megamek/src/megamek/client/ui/WrapLayout.java
Labels: Bug, Refactoring

#6076 Minor gui scaling fixes
  megamek/src/megamek/client/ui/swing/BayMunitionsChoicePanel.java
  megamek/src/megamek/client/ui/swing/MMToggleButton.java
Labels: GUI

#6096 Fix Typo in Availability List for Dragonfly (Viper) Chassis
  megamek/data/forcegenerator/2950.xml
Labels: Data

#6105 Set Dialog Always on Top in `AbstractIconChooserDialog`
  megamek/src/megamek/client/ui/dialogs/AbstractIconChooserDialog.java
Labels: Bug, GUI

#6125 Two minor spelling/capitalization fixes.
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
Labels: Severity: Low

#6130 Fixed Portrait Folder Contents
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_12.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_14.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_18.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_19.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_20.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_3.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_7.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_8.png
  megamek/data/images/portraits/Female/Aerospace Tech/AeroTek_F_9.png
Labels: Bug

#6133 More minor spelling/capitalization fixes.
  megamek/i18n/megamek/common/options/messages.properties
Labels: Severity: Low

#6139 Renamed MekTech Portrait Folder to Mek Tech
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_1.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_10.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_11.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_12.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_13.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_14.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_15.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_16.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_17.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_18.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_19.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_2.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_20.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_21.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_22.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_23.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_3.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_4.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_5.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_6.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_7.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_8.png
  megamek/data/images/portraits/Female/Mek Tech/MekTech_F_9.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_1.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_10.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_11.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_12.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_13.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_14.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_15.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_16.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_17.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_18.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_19.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_2.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_20.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_21.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_22.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_23.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_24.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_25.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_26.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_3.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_4.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_5.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_6.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_7.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_8.png
  megamek/data/images/portraits/Male/Mek Tech/MechTek_M_9.png
Labels: Bug, MHQ-origin MM Issues

#5436 lightning storm updates
  megamek/i18n/megamek/common/options/messages.properties
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/common/Sensor.java
  megamek/src/megamek/common/actions/WeaponAttackAction.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/common/planetaryconditions/PlanetaryConditions.java
  megamek/src/megamek/common/planetaryconditions/Weather.java
  megamek/src/megamek/common/util/BoardUtilities.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/src/megamek/server/totalwarfare/TWPhasePreparationManager.java
Labels: Planetary Conditions
