Repository MegaMek/megamek, pull requests merged in 2025-10, with the labels that each got.

#7460 Improvement: Bolstered Clan Forces
  megamek/src/megamek/common/universe/HonorRating.java
Labels: MHQ-origin MM Issues

#7459 Improvement: Added Date Utilities Class
  megamek/src/megamek/common/util/DateUtilities.java
Labels: Utility

#7450 Optimize leg location searches
  megamek/src/megamek/common/units/BipedMek.java
  megamek/src/megamek/common/units/QuadMek.java
  megamek/src/megamek/common/units/TripodMek.java
Labels: For New Dev Cycle
