Repository MegaMek/megamek, pull requests merged in 2025-03, with the labels that each got.

#6616 Fix 6604: Fuel Air Explosives do no damage to off-board units
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#6615 feat: More princess commands - ignore player/turret, order offboard artillery
  megamek/i18n/megamek/client/bot/messages.properties
  megamek/src/megamek/client/bot/princess/ArtilleryCommandAndControl.java
  megamek/src/megamek/client/bot/princess/ArtilleryTargetingControl.java
  megamek/src/megamek/client/bot/princess/ChatCommands.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/commands/ArtilleryCommand.java
  megamek/src/megamek/client/bot/princess/commands/IgnorePlayerCommand.java
  megamek/src/megamek/client/bot/princess/commands/IgnoreTurretsCommand.java
  megamek/src/megamek/client/ui/swing/commands/ClientCommandPanel.java
  megamek/src/megamek/server/commands/arguments/NotRequiredMultiHexNumberArgument.java
Labels: Princess/AI, PACAR

#6626 fix: ejected crew, ignored targets and broken enemies wont be target of physical attacks anymore
  megamek/src/megamek/client/bot/PhysicalCalculator.java
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/FireControl.java
  megamek/src/megamek/client/bot/princess/InfantryPathRanker.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/UtilityPathRanker.java
Labels: Princess/AI, PACAR

#6646 fix: added missing copyright notice
  megamek/src/megamek/client/ui/baseComponents/AbstractNagDialog.java
  megamek/src/megamek/client/ui/dialogs/AutoResolveChanceDialog.java
  megamek/src/megamek/client/ui/dialogs/AutoResolveProgressDialog.java
  megamek/src/megamek/client/ui/dialogs/AutoResolveSimulationLogDialog.java
  megamek/src/megamek/client/ui/dialogs/nagDialogs/BotReadmeNagDialog.java
  megamek/src/megamek/client/ui/swing/util/MenuScroller.java
  megamek/src/megamek/common/CubeCoords.java
  megamek/src/megamek/common/event/PostGameResolution.java
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/strategicBattleSystems/BaseFormationConverter.java
  megamek/src/megamek/common/weapons/FlamerHandlerHelper.java
  megamek/src/megamek/test/ScenarioLoaderTest.java
  megamek/src/megamek/utilities/GifWriter.java
  megamek/src/megamek/utilities/GifWriterThread.java
  megamek/unittests/megamek/client/ui/SharedUtilityTest.java
  megamek/unittests/megamek/common/weapons/ArtilleryWeaponIndirectHomingHandlerTest.java
Labels: ACAR

#6667 feat: allow princess to deploy mines in random clear hexes on the map
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/MinefieldDeploymentPlanner.java
  megamek/src/megamek/client/bot/RandomMinefieldDeploymentPlanner.java
Labels: Princess/AI

#6653 fix: fixes AeroDamageApplier so it stops killing aero units
  megamek/src/megamek/common/autoresolve/acar/phase/VictoryPhase.java
  megamek/src/megamek/common/autoresolve/acar/report/StartingScenarioPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/VictoryPhaseReporter.java
  megamek/src/megamek/common/autoresolve/damage/AeroDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/DamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/EntityFinalState.java
  megamek/src/megamek/common/autoresolve/damage/MekDamageApplier.java
Labels: MHQ-origin MM Issues, ACAR

#6655 fix: adds fallback to default skin if it cant load the skin
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/widget/SkinXMLHandler.java
Labels: Bug

#6656 fix: I hope this fixes the problem of trying to save GIFs
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/ClientGUI.java
Labels: GUI

#6670 fix: makes gif writer finish the gif at victory phase
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/utilities/GifWriter.java
  megamek/src/megamek/utilities/GifWriterThread.java
Labels: GUI

#6674 Added Check for Gender Neutral Pronouns
  megamek/src/megamek/common/enums/Gender.java
Labels: Utility

#6693 fix: reset minefield density was missing the null check before trying…
  megamek/src/megamek/common/Game.java
Labels: Bug, Princess/AI

#6694 fix: gracefully close gifWritter, and gracefully initialize it on a second run
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/utilities/GifWriterThread.java
Labels: GUI, MHQ-origin MM Issues

#6703 Updated SkillLevel to Use Arbitrary Values Instead of Ordinal
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: Refactoring

#6695 feat: changed experimental features for Princess
  megamek/src/megamek/ai/optimizer/UtilityPathRankerCostFunction.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/SwarmContext.java
  megamek/src/megamek/client/bot/princess/UtilityPathRanker.java
Labels: PACAR

#6710 Fix/unit state serde
  megamek/build.gradle
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/ai/dataset/DatasetParser.java
  megamek/src/megamek/ai/dataset/TrainingDataset.java
  megamek/src/megamek/ai/dataset/UnitActionSerde.java
  megamek/src/megamek/ai/dataset/UnitState.java
  megamek/src/megamek/ai/dataset/UnitStateField.java
  megamek/src/megamek/ai/dataset/UnitStateSerde.java
  megamek/src/megamek/ai/optimizer/BasicPathRankerCostFunction.java
  megamek/src/megamek/ai/optimizer/BehaviorState.java
  megamek/src/megamek/ai/optimizer/Checkpoint.java
  megamek/src/megamek/ai/optimizer/CostFunction.java
  megamek/src/megamek/ai/optimizer/CostFunctionChooser.java
  megamek/src/megamek/ai/optimizer/ExtendedCostFunction.java
  megamek/src/megamek/ai/optimizer/ModelParameter.java
  megamek/src/megamek/ai/optimizer/ParameterOptimizer.java
  megamek/src/megamek/ai/optimizer/Parameters.java
  megamek/src/megamek/ai/optimizer/UtilityPathRankerCostFunction.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineFlag.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/utilities/PrincessFineTuning.java
Labels: Bug, Refactoring, PACAR

#6718 Added 2,319 New Callsigns
  megamek/data/names/callsigns.csv
Labels: Data

#6719 Corrected Capitalization in Surnames Data
  megamek/data/names/surnames.csv
Labels: Data

#6724 Added 694 Brand New Callsigns
  megamek/data/names/callsigns.csv
Labels: Data

#6737 Data corrections
  megamek/data/mekfiles/battlearmor/3145/NTNU RS/Gray Death Strike Suit (HarJel)(Sqd4).blk
  megamek/data/mekfiles/battlearmor/3145/NTNU RS/Gray Death Strike Suit (HarJel)(Sqd5).blk
  megamek/data/mekfiles/battlearmor/3145/NTNU RS/Gray Death Strike Suit (HarJel)(Sqd6).blk
  megamek/data/mekfiles/ge/Archive_Turrets/Clan/Special/VGL (Dual) Turret.blk
  megamek/data/mekfiles/ge/Archive_Turrets/Clan/Special/VGL (Quad) Turret.blk
  megamek/data/mekfiles/ge/Archive_Turrets/Clan/Special/VGL (Single) Turret.blk
  megamek/data/mekfiles/ge/Archive_Turrets/Clan/Special/VGL (Triple) Turret.blk
  megamek/data/mekfiles/ge/Medium Turrets/Medium Shredder Turret 3057.blk
  megamek/src/megamek/common/WeaponType.java
  megamek/src/megamek/common/weapons/mortars/CLVehicularGrenadeLauncher.java
Labels: Data

#6736 replace former ISDroneExtra equipment in unit files with :SIZE: data
  megamek/data/mekfiles/dropships/TRO3145/Republic/Duat Military Transport.blk
  megamek/data/mekfiles/vehicles/3039u/Hi-Scout Drone Carrier.blk
  megamek/data/mekfiles/vehicles/XTRs/Phantoms/Hi-Scout Drone Carrier (Cunnington).blk
  megamek/data/mekfiles/vehicles/XTRs/Republic I/Diggs Drone Control Tank.blk
Labels: Data

#6779 Fixed Missing Prone Modifier in Weapon Attack Calculation
  megamek/src/megamek/common/actions/WeaponAttackAction.java
Labels: Bug, Severity: Medium

#6777 Added Missing Handheld Weapon Unit Type to Messages Properties
  megamek/i18n/megamek/common/messages.properties
Labels: Bug, Severity: Low

#6774 Removed 3 Duplicate Callsigns
  megamek/data/names/callsigns.csv
Labels: Bug, Data, Severity: Low
