Repository MegaMek/megamek, pull requests merged in 2025-06, with the labels that each got.

#7196 fix: stop erroneously testing MiscType flag on non misc type things.
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#7233 fix: now the rolling logs are even better, with automatic compression…
  megamek/mmconf/log4j2.xml
  megamek/src/megamek/client/bot/BotLogger.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/logging/MMLogger.java
Labels: (RFE) Enhancement, Refactoring

#7254 Feature: Added PDFReaderPanel – Embedded Swing PDF Viewer
  megamek/build.gradle
  megamek/resources/megamek/common/PDFReaderPanel.properties
  megamek/src/megamek/utilities/PDFReaderPanel.java
Labels: Utility, New Feature

#7253 PR: Force Display Improvements
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/buttons/MMToggleButton.java
  megamek/src/megamek/client/ui/clientGUI/GUIPreferences.java
  megamek/src/megamek/client/ui/clientGUI/tooltip/UnitToolTip.java
  megamek/src/megamek/client/ui/dialogs/forceDisplay/ForceDisplayMekCellFormatter.java
  megamek/src/megamek/client/ui/dialogs/forceDisplay/ForceDisplayMekTreeRenderer.java
  megamek/src/megamek/client/ui/dialogs/forceDisplay/ForceDisplayPanel.java
  megamek/src/megamek/common/Crew.java
Labels: Improvement to Existing Feature

#7259 Improvement: Added 'setTags' Method to New Faction Class
  megamek/src/megamek/common/universe/Faction2.java
Labels: Utility

#7265 Improvement: Added Aggregate Faction Tag
  megamek/data/universe/factions/ABN.yml
  megamek/data/universe/factions/BAN.yml
  megamek/data/universe/factions/CLAN.yml
  megamek/data/universe/factions/CM.yml
  megamek/data/universe/factions/DIS.yml
  megamek/data/universe/factions/IND.yml
  megamek/data/universe/factions/IS.yml
  megamek/data/universe/factions/MERC.yml
  megamek/data/universe/factions/NONE.yml
  megamek/data/universe/factions/PIR.yml
  megamek/data/universe/factions/Periphery.yml
  megamek/data/universe/factions/REB.yml
  megamek/data/universe/factions/RON.yml
  megamek/data/universe/factions/UND.yml
  megamek/src/megamek/common/universe/Faction2.java
  megamek/src/megamek/common/universe/FactionTag.java
Labels: Data, Utility

#7266 Improvement: Added Rank System Code to Faction Data
  megamek/data/universe/factions/ARC.yml
  megamek/data/universe/factions/CC.yml
  megamek/data/universe/factions/CS.yml
  megamek/data/universe/factions/DC.yml
  megamek/data/universe/factions/FC.yml
  megamek/data/universe/factions/FRR.yml
  megamek/data/universe/factions/FS.yml
  megamek/data/universe/factions/FWL.yml
  megamek/data/universe/factions/LA.yml
  megamek/data/universe/factions/MH.yml
  megamek/data/universe/factions/MOC.yml
  megamek/data/universe/factions/OA.yml
  megamek/data/universe/factions/TC.yml
  megamek/data/universe/factions/WOB.yml
  megamek/src/megamek/common/universe/Faction2.java
Labels: Data, Utility
