Repository MegaMek/megamek, pull requests merged in 2025-05, with the labels that each got.

#6953 Fix: Fixed Quad-Vees Taking PSRs and Falling While in Vehicle Mode
  megamek/docs/history.txt
  megamek/src/megamek/common/QuadVee.java
Labels: Bug, Severity: Medium

#6964 Fix: Added Missing Machine Gun Burst Fire Toggle Label in Edit Unit Dialog
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/panels/RapidFireMGPanel.java
Labels: Bug, GUI, Severity: Medium

#6958 Fix: Add scroll on unit display dialog (tabbed view)
  .gitignore
  megamek/docs/history.txt
  megamek/src/megamek/client/ui/dialogs/DisposableDisplayContainer.java
  megamek/src/megamek/client/ui/dialogs/SharedDisplayContainer.java
  megamek/src/megamek/client/ui/dialogs/UnitDisplayContainer.java
  megamek/src/megamek/client/ui/dialogs/UnitDisplayDialog.java
  megamek/src/megamek/client/ui/swing/unitDisplay/ArmorPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/ExtraPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/PilotPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/SummaryPanel.java
  megamek/src/megamek/client/ui/swing/unitDisplay/UnitDisplay.java
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/client/ui/swing/widget/ArmlessMekMapSet.java
Labels: Bug, GUI

#6977 Fix: #6976 Prevent performance issues caused by the unit display's weapon panel from freezing the game
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
Labels: Bug, GUI, Blocker, Severity: Critical

#6975 Fix for Unit Sale Costs being generally incorrect - Megamek part
  megamek/src/megamek/common/Tank.java
Labels: Bug, Cost

#6979 Fix: #6967 Battlemech Shields are non-functional
  megamek/src/megamek/common/MekWithArms.java
Labels: Bug

#6985 fix: moves minefield marker to its appropriate hex (issue #1783) and …
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_de.properties
  megamek/i18n/megamek/client/messages_es.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
Labels: Bug

#6987 fix: c3 at extreme ranges now responds with the correct range bracket…
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/RangeType.java
Labels: Bug

#6984 Fix: makes sure Mast Mount and its equipments aren't destroyed if the rotor takes 0 damage
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#6973 fix: i18n support for sorters, reduced a bit the code duplication, prevents NPE if player is null
  megamek/i18n/megamek/client/sorters.properties
  megamek/i18n/megamek/client/sorters_en.properties
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/BVSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/C3IDSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/IDSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/MekTableSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/MekTreeTopLevelSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/NameSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerBVSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerTonnageSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerTransportIDSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/PlayerUnitRoleSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/Sorting.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/TonnageSorter.java
  megamek/src/megamek/client/ui/swing/lobby/sorters/TypeSorter.java
  megamek/src/megamek/common/AbstractGame.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/UnitRole.java
  megamek/src/megamek/common/internationalization/I18n.java
Labels: Bug, Sentry

#6978 Fix: MacOS and Linux users can now open the right-click popup contextual menu on force view
  megamek/src/megamek/client/ui/dialogs/SBFStatsDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
Labels: Bug, Accessibility, GUI, Severity: Critical

#6981 fix: stop meks making DFA into water from walking above water, add small quality of life for physical attack reports
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/Report.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/unittests/megamek/common/EntityTest.java
  megamek/unittests/megamek/common/JumpshipTest.java
  megamek/unittests/megamek/common/MekFileParserTest.java
  megamek/unittests/megamek/common/autoresolve/damage/DamageApplierChooserTest.java
  megamek/unittests/megamek/logging/MMLoggerTest.java
Labels: Bug, Severity: Medium

#6992 fix NPE in report display when getSelectedItem is null
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
Labels: Bug

#6991 fix: fixed error with armor calculation which would not lower-cap the value at zero.
  megamek/src/megamek/common/battlevalue/BVCalculator.java
  megamek/src/megamek/common/battlevalue/BattleArmorBVCalculator.java
  megamek/src/megamek/common/battlevalue/DropShipBVCalculator.java
  megamek/src/megamek/common/battlevalue/HandheldWeaponBVCalculator.java
Labels: Bug, BV

#6959 added dispose() on some dialogs (fix memory leaks)
  megamek/docs/history.txt
  megamek/src/megamek/client/ui/dialogs/ASConversionInfoDialog.java
  megamek/src/megamek/client/ui/dialogs/ASStatsDialog.java
  megamek/src/megamek/client/ui/dialogs/AutoResolveChanceDialog.java
  megamek/src/megamek/client/ui/dialogs/CostDisplayDialog.java
  megamek/src/megamek/client/ui/dialogs/EntityReadoutDialog.java
  megamek/src/megamek/client/ui/dialogs/SBFStatsDialog.java
  megamek/src/megamek/client/ui/dialogs/WeightDisplayDialog.java
Labels: GUI

#7012 [ACAR] Fix: formation convertion now checks if there are units forceless and handles it
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/autoresolve/Resolver.java
  megamek/src/megamek/common/autoresolve/component/AcTurn.java
  megamek/src/megamek/common/autoresolve/component/EngagementControl.java
  megamek/src/megamek/common/autoresolve/component/Formation.java
  megamek/src/megamek/common/autoresolve/component/FormationTurn.java
  megamek/src/megamek/common/autoresolve/converter/EntityAsFormation.java
  megamek/src/megamek/common/autoresolve/converter/EntityAsUnit.java
  megamek/src/megamek/common/autoresolve/converter/FlattenForces.java
  megamek/src/megamek/common/autoresolve/converter/ForceConsolidation.java
  megamek/src/megamek/common/autoresolve/converter/KeepCurrentForces.java
  megamek/src/megamek/common/autoresolve/converter/LowestForceAsUnit.java
  megamek/src/megamek/common/autoresolve/converter/MMSetupForces.java
  megamek/src/megamek/common/autoresolve/converter/SetupForces.java
  megamek/src/megamek/common/autoresolve/converter/SingletonForces.java
  megamek/src/megamek/common/autoresolve/damage/AeroDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/DamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/DamageApplierChooser.java
  megamek/src/megamek/common/autoresolve/damage/EntityFinalState.java
  megamek/src/megamek/common/autoresolve/damage/GunEmplacementDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/InfantryDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/MekDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/SimpleDamageApplier.java
  megamek/src/megamek/common/autoresolve/damage/TankDamageApplier.java
  megamek/src/megamek/common/autoresolve/event/AutoResolveConcludedEvent.java
Labels: Bug, ACAR

#7011 [ACAR] Fix OutOfBounds exception when resolving ammo explosion
  megamek/src/megamek/common/autoresolve/damage/DamageApplier.java
Labels: Bug, ACAR

#7016 fix: fixes the final facing facing modifier for princess, adds a few special case handlings and tests
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/FacingDiffCalculator.java
  megamek/src/megamek/client/bot/princess/IPathRanker.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/UnitsMedianCoordinateCalculator.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/FacingDiffCalculatorTest.java
  megamek/unittests/megamek/client/bot/princess/UnitsMedianCoordinateCalculatorTest.java
Labels: Princess/AI, PACAR

#7022 PR: Data updates - Early Mek availability (2398-2571)
  megamek/data/forcegenerator/2398.xml
  megamek/data/forcegenerator/2440.xml
  megamek/data/forcegenerator/2460.xml
  megamek/data/forcegenerator/2470.xml
  megamek/data/forcegenerator/2490.xml
  megamek/data/forcegenerator/2520.xml
  megamek/data/forcegenerator/2571.xml
Labels: Data

#7024 fix: Restore firing solution displaying after a torso twist
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/phaseDisplay/FiringDisplay.java
Labels: GUI

#7013 fix: stops an NPE on PhysicalDisplay when it tries to set a value on entity dodging
  megamek/src/megamek/client/ui/swing/phaseDisplay/PhysicalDisplay.java
Labels: Bug, GUI

#7017 fix: fixing messages for princess when responding requests
  megamek/i18n/megamek/client/bot/messages.properties
  megamek/src/megamek/client/bot/princess/commands/BloodFeudCommand.java
  megamek/src/megamek/client/bot/princess/commands/IgnorePlayerCommand.java
  megamek/src/megamek/client/bot/princess/commands/IgnoreTargetCommand.java
  megamek/src/megamek/client/bot/princess/commands/IgnoreTurretsCommand.java
Labels: Bug, Princess/AI

#7019 feat: expose Princess new external levers to allow players to spice things up
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/client/messages_es.properties
  megamek/i18n/megamek/client/messages_ru.properties
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/bot/princess/FacingDiffCalculator.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/UnitsMedianCoordinateCalculator.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/dialogs/BotConfigTargetHexDialog.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/FacingDiffCalculatorTest.java
Labels: Princess/AI, PACAR

#7026 Fix: #7020 Hide Sprites for Units that mount into bays
  megamek/src/megamek/server/totalwarfare/MovePathHandler.java
Labels: Bug, Severity: High

#7021 feat: you can setup so princess herd only with her own units
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
Labels: Princess/AI, PACAR

#7028 fix: Log Rolls now properly logs the roll as public so it stops complaining that there is no subject
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/MMRoll.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#7042 fix: fixes the BV cost and CBills cost for some missile munition types
  megamek/src/megamek/common/AmmoType.java
Labels: BV

#7045 Fix: Fixed Naming of MekTech Portrait Folders
  megamek/data/images/portraits/Female/MekTech/MekTech_F_1.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_10.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_11.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_12.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_13.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_14.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_15.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_16.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_17.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_18.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_19.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_2.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_20.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_21.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_22.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_23.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_3.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_4.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_5.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_6.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_7.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_8.png
  megamek/data/images/portraits/Female/MekTech/MekTech_F_9.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_1.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_10.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_11.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_12.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_13.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_14.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_15.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_16.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_17.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_18.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_19.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_2.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_20.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_21.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_22.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_23.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_24.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_25.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_26.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_3.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_4.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_5.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_6.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_7.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_8.png
  megamek/data/images/portraits/Male/MekTech/MechTek_M_9.png
  megamek/src/megamek/common/icons/AbstractIcon.java
Labels: Bug, Data, Severity: Medium

#7050 fix: stops jumps from being made into buildings through roofs
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/FloorTarget.java
  megamek/src/megamek/common/LosEffects.java
  megamek/src/megamek/common/MoveStep.java
  megamek/src/megamek/common/enums/BuildingType.java
  megamek/unittests/megamek/common/movepath/JumpTest.java
Labels: Bug, Infantry

#7056 Fix: #7052 Prevent Princess from freezing if theres a stacking violation while trying to abandon a unit
  megamek/src/megamek/client/bot/princess/Princess.java
Labels: Bug, Princess/AI, Severity: Critical, Transportation

#7080 fix: minimap and unit display and mini report dialog priority against other windows
  megamek/src/megamek/client/ui/swing/ClientGUI.java
Labels: Bug, GUI, Unit Display, PACAR

#7078 fix: AmmoBin selection switching back to the first AmmoBin in the weapons display
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/MiscType.java
  megamek/src/megamek/common/WeaponType.java
Labels: Bug, GUI, Unit Display, Sentry

#7085 fix: ammobin selector not staying in the selected ammo
  megamek/src/megamek/client/ui/swing/unitDisplay/WeaponPanel.java
Labels: Bug, GUI, Unit Display, Severity: Medium

#7088 Fix accidental fall damage doing insufficient damage to victims under falling unit
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/unittests/megamek/common/ComputeTest.java
Labels: Bug

#7093 fix: Multi-purpose missile is supposed to be BA LRM only
  megamek/src/megamek/common/AmmoType.java
Labels: Data

#7092 fix: unit tooltip fixed for aero, also fixed one mistake with html tags for pilot tooltip
  megamek/src/megamek/client/ui/swing/tooltip/PilotToolTip.java
  megamek/src/megamek/client/ui/swing/tooltip/UnitToolTip.java
  megamek/src/megamek/common/Entity.java
Labels: Bug, Aerospace, GUI

#6971 fix: adds padding in between maps if they are of odd width size, making it possible to tile those. Small performance improvements.
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/util/UIUtil.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Hex.java
  megamek/src/megamek/common/board/postprocess/TWBoardTransformer.java
  megamek/src/megamek/common/jacksonadapters/BoardDeserializer.java
  megamek/src/megamek/common/scenario/ScenarioV1.java
  megamek/src/megamek/common/util/BoardUtilities.java
  megamek/src/megamek/server/ServerBoardHelper.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Performance, For New Dev Cycle, Severity: Critical, Map and Board

#6996 Feature: Added Tracking of Heroic and Legendary Skill Levels
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: For New Dev Cycle, Implementation of Missing Official Rule

#7072 Feat: Ground Combat Implementation of Booby Trap
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/client/ui/swing/unitDisplay/SystemPanel.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EquipmentMode.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/MiscType.java
  megamek/src/megamek/common/Mounted.java
  megamek/src/megamek/common/TechAdvancement.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/src/megamek/server/totalwarfare/TWPhaseEndManager.java
Labels: Implementation of Missing Official Rule

#6944 feat: adds CONVOY behavior setting preset and flag to ignore damage output on pathing
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/UtilityPathRanker.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/codeUtilities/MathUtility.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsFactoryTest.java
Labels: Princess/AI, Conflicts, PACAR

#7057 Fix: fixed a couple more problems with jumping in and out of buildings with BA/Infantry and Nags for jumping into buildings
  megamek/src/megamek/client/ui/SharedUtility.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Building.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/moves/MoveStep.java
  megamek/unittests/megamek/common/GameBoardTestCase.java
  megamek/unittests/megamek/common/StepLog.java
  megamek/unittests/megamek/common/movepath/JumpTest.java
  megamek/unittests/megamek/common/moves/BattleArmorTest.java
  megamek/unittests/megamek/common/moves/InfantryMovementTest.java
  megamek/unittests/megamek/common/moves/JumpTest.java
Labels: Bug, Infantry

#7094 Fix: BA SRM and LRM ammo fixes and stop Clan and IS from sharing ammo unless option is enabled.
  megamek/i18n/megamek/common/options/messages.properties
  megamek/i18n/megamek/common/options/messages_de.properties
  megamek/i18n/megamek/common/options/messages_es.properties
  megamek/i18n/megamek/common/options/messages_ru.properties
  megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
  megamek/src/megamek/client/ui/swing/panels/WeaponAmmoChoicePanel.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/AmmoTypeFlag.java
  megamek/src/megamek/common/options/GameOptions.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/common/scenario/ScenarioV1.java
Labels: Bug

#6935 board editor - trace overlay
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/BoardEditor.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/boardview/overlay/TraceOverlay.java
Labels: Map Editor, For New Dev Cycle

#7113 Feat: add new tags to board tagger
  megamek/src/megamek/utilities/BoardsTagger.java
Labels: Map and Board

#7124 Improvement: Added UI Gray Utility Method
  megamek/src/megamek/client/ui/swing/util/UIUtil.java
Labels: Utility

#7130 fix: issue #7123, now show possible moves and show best modifiers don't count illegal moves
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/boardview/spriteHandler/MovementModifierSpriteHandler.java
  megamek/src/megamek/client/ui/swing/phaseDisplay/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/phaseDisplay/dialog/ManeuverChoiceDialog.java
  megamek/src/megamek/common/pathfinder/ShortestPathFinder.java
Labels: GUI, Movement

#7135 fix: makes aerodyne stop thinking it will overlap itself while taxing after deployment
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/Dropship.java
  megamek/src/megamek/common/IAero.java
  megamek/src/megamek/common/LandAirMek.java
  megamek/src/megamek/common/util/ConditionalStringJoiner.java
Labels: Aerospace, Movement

#7140 Feat: Favorite Bot Behavior Setting
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/clientGUI/ClientGUI.java
  megamek/src/megamek/client/ui/dialogs/buttonDialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/dialogs/buttonDialogs/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/dialogs/buttonDialogs/EditBotsDialog.java
  megamek/src/megamek/client/ui/panels/phaseDisplay/lobby/ChatLounge.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: Princess/AI, ACAR, PACAR

#7152 Yaml export
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/BombType.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/TechAdvancement.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/common/util/YamlEncDec.java
  megamek/src/megamek/common/util/YamlSerializerEquipmentType.java
  megamek/src/megamek/common/weapons/AltitudeBombAttack.java
  megamek/src/megamek/common/weapons/DiveBombAttack.java
  megamek/src/megamek/common/weapons/SpaceBombAttack.java
  megamek/src/megamek/common/weapons/bombs/BombISRL10.java
  megamek/src/megamek/common/weapons/other/ISFireExtinguisher.java
Labels: Refactoring

#7184 fix: fix the error where tooltip would show on discord and text copy/paste
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/common/MekView.java
Labels: GUI
