Repository MegaMek/megamek, pull requests merged in 2025-01, with the labels that each got.

#6335 default the directory filter to Select All in Advanced Board Search
  megamek/src/megamek/client/ui/advancedSearchMap/AdvancedSearchMapDialog.java
Labels: Map and Board

#6328 Building type enum
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/dialogs/BotConfigTargetHexDialog.java
  megamek/src/megamek/common/Board.java
  megamek/src/megamek/common/Building.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/MoveStep.java
  megamek/src/megamek/common/actions/FindClubAction.java
  megamek/src/megamek/common/enums/BuildingType.java
  megamek/src/megamek/common/util/BoardUtilities.java
  megamek/src/megamek/common/util/BuildingTemplate.java
  megamek/src/megamek/common/util/CityBuilder.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/src/megamek/utilities/BoardsTagger.java
Labels: For New Dev Cycle

#6343 Fix: Tank armor and invalid builds
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKTankFile.java
  megamek/src/megamek/common/verifier/TestAdvancedAerospace.java
  megamek/src/megamek/common/verifier/TestAero.java
  megamek/src/megamek/common/verifier/TestBattleArmor.java
  megamek/src/megamek/common/verifier/TestEntity.java
  megamek/src/megamek/common/verifier/TestInfantry.java
  megamek/src/megamek/common/verifier/TestMek.java
  megamek/src/megamek/common/verifier/TestProtoMek.java
  megamek/src/megamek/common/verifier/TestSmallCraft.java
  megamek/src/megamek/common/verifier/TestSupportVehicle.java
  megamek/src/megamek/common/verifier/TestTank.java
  megamek/unittests/megamek/common/loaders/BulkUnitFileTest.java
Labels: Bug

#6375 fix: fixes a class cast bug and an error in the argument parsing algorithm
  megamek/src/megamek/server/commands/ClientServerCommand.java
  megamek/src/megamek/server/commands/NukeCommand.java
Labels: Bug

#6376 fix: makes the end command work
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#6407 Feat/acar formations reintroduced
  megamek/data/css/acarCssFile.css
  megamek/i18n/megamek/client/acs-report-messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/client/ui/dialogs/AutoResolveProgressDialog.java
  megamek/src/megamek/client/ui/dialogs/helpDialogs/AbstractHelpDialog.java
  megamek/src/megamek/common/BattleArmor.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/autoresolve/Resolver.java
  megamek/src/megamek/common/autoresolve/acar/SimulationContext.java
  megamek/src/megamek/common/autoresolve/acar/SimulationManager.java
  megamek/src/megamek/common/autoresolve/acar/handler/StandardUnitAttackHandler.java
  megamek/src/megamek/common/autoresolve/acar/handler/WithdrawActionHandler.java
  megamek/src/megamek/common/autoresolve/acar/order/Order.java
  megamek/src/megamek/common/autoresolve/acar/order/Orders.java
  megamek/src/megamek/common/autoresolve/acar/phase/EndPhase.java
  megamek/src/megamek/common/autoresolve/acar/phase/FiringPhase.java
  megamek/src/megamek/common/autoresolve/acar/phase/MovementPhase.java
  megamek/src/megamek/common/autoresolve/acar/report/AttackReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/DummyAttackReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/DummyEndPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/DummyWithdrawReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/EndPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/EntityNameReportEntry.java
  megamek/src/megamek/common/autoresolve/acar/report/FormationReportEntry.java
  megamek/src/megamek/common/autoresolve/acar/report/HtmlGameLogger.java
  megamek/src/megamek/common/autoresolve/acar/report/IAttackReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/IEndPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/IWithdrawReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/RecoveringNerveActionReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/StartingScenarioPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/UnitReportEntry.java
  megamek/src/megamek/common/autoresolve/acar/report/VictoryPhaseReporter.java
  megamek/src/megamek/common/autoresolve/acar/report/WithdrawReporter.java
  megamek/src/megamek/common/autoresolve/component/Formation.java
  megamek/src/megamek/common/autoresolve/converter/EntityAsFormation.java
  megamek/src/megamek/common/autoresolve/converter/EntityAsUnit.java
  megamek/src/megamek/common/autoresolve/converter/FlattenForces.java
  megamek/src/megamek/common/autoresolve/converter/ForceConsolidation.java
  megamek/src/megamek/common/autoresolve/converter/KeepCurrentForces.java
  megamek/src/megamek/common/autoresolve/converter/LowestForceAsUnit.java
  megamek/src/megamek/common/autoresolve/converter/MMSetupForces.java
  megamek/src/megamek/common/autoresolve/converter/SingletonForces.java
  megamek/src/megamek/common/autoresolve/converter/SortSBFValidForces.java
  megamek/src/megamek/common/autoresolve/damage/InfantryDamageApplier.java
  megamek/src/megamek/common/force/Forces.java
  megamek/src/megamek/common/util/CollectionUtil.java
  megamek/src/megamek/common/util/Counter.java
  megamek/src/megamek/server/ServerLobbyHelper.java
Labels: ACAR

#6409 Campaign Options IIC - MegaMek Portion
  megamek/src/megamek/client/ui/swing/util/FlatLafStyleBuilder.java
Labels: Utility

#6415 fix: fixes an error where force consolidation would not set the correct owner of the force
  megamek/src/megamek/common/autoresolve/acar/SimulationContext.java
  megamek/src/megamek/common/autoresolve/converter/FlattenForces.java
  megamek/src/megamek/common/autoresolve/converter/ForceConsolidation.java
  megamek/src/megamek/common/autoresolve/converter/KeepCurrentForces.java
  megamek/src/megamek/common/autoresolve/converter/MMSetupForces.java
  megamek/src/megamek/common/autoresolve/converter/SetupForces.java
  megamek/src/megamek/common/autoresolve/converter/SingletonForces.java
  megamek/src/megamek/common/autoresolve/converter/SortSBFValidForces.java
Labels: ACAR

#6414 Active Contract Warning on Campaign Load - MegaMek Portion
  megamek/src/megamek/SuiteConstants.java
Labels: Utility

#6427 fix: makes princess actually ignore ignored targets
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/princess/FireControl.java
  megamek/src/megamek/client/bot/princess/NewtonianAerospacePathRanker.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/RankedPath.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
Labels: Princess/AI

#6429 Issue 6359: LAMs now properly consider if they're in fighter mode or not when deploying.
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: Bug

#6418 feat: Headless client, Commander GUI, Bot Commands panel
  megamek/docs/ACAR & PACAR - Abstract Combat Auto Resolve/ACAR-Abstract Combat Auto Resolve documentation.pdf
  megamek/docs/ACAR & PACAR - Abstract Combat Auto Resolve/Commander GUI - how to use it.txt
  megamek/docs/ACAR & PACAR - Abstract Combat Auto Resolve/PACAR & Commanders GUI.pdf
  megamek/docs/ACAR - Abstract Combat Auto Resolve/ACAR-Abstract Combat Auto Resolve documentation.pdf
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/src/megamek/MMConstants.java
  megamek/src/megamek/client/AbstractClient.java
  megamek/src/megamek/client/HeadlessClient.java
  megamek/src/megamek/client/IClient.java
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/princess/ChatCommands.java
  megamek/src/megamek/client/ui/dialogs/BotCommandsPanel.java
  megamek/src/megamek/client/ui/dialogs/MiniReportDisplayDialog.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommanderGUI.java
  megamek/src/megamek/client/ui/swing/CommonMenuBar.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/IDisconnectSilently.java
  megamek/src/megamek/client/ui/swing/IHasBoardView.java
  megamek/src/megamek/client/ui/swing/IHasCurrentPanel.java
  megamek/src/megamek/client/ui/swing/IHasMenuBar.java
  megamek/src/megamek/client/ui/swing/IHasUnitDisplay.java
  megamek/src/megamek/client/ui/swing/ILocalBots.java
  megamek/src/megamek/client/ui/swing/MiniReportDisplay.java
  megamek/src/megamek/client/ui/swing/SBFClientGUI.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/minimap/BoardviewlessMinimap.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/overlay/ChatOverlay.java
  megamek/src/megamek/client/ui/swing/overlay/IFF.java
  megamek/src/megamek/client/ui/swing/overlay/OverlayPainter.java
  megamek/src/megamek/client/ui/swing/overlay/OverlayPanel.java
  megamek/src/megamek/client/ui/swing/util/KeyCommandBind.java
  megamek/src/megamek/common/Aero.java
  megamek/src/megamek/common/AeroSpaceFighter.java
  megamek/src/megamek/common/BipedMek.java
  megamek/src/megamek/common/ConvFighter.java
  megamek/src/megamek/common/Dropship.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/GunEmplacement.java
  megamek/src/megamek/common/Jumpship.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/SmallCraft.java
  megamek/src/megamek/common/SpaceStation.java
  megamek/src/megamek/common/autoresolve/acar/SimulatedClient.java
  megamek/src/megamek/common/autoresolve/converter/LowestForceAsUnit.java
  megamek/src/megamek/common/autoresolve/converter/SingletonForces.java
  megamek/src/megamek/common/autoresolve/converter/SortSBFValidForces.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
Labels: ACAR

#6433 Princess - Chat Commands fix
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/princess/ChatCommands.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/unittests/megamek/client/bot/ChatProcessorTest.java
  megamek/unittests/megamek/client/bot/princess/PrincessTest.java
Labels: Princess/AI

#6425 Issue 6390: Units switching from multi-hex to single-hex and vice-versa properly update the entityPosLookup cache
  megamek/src/megamek/common/Dropship.java
  megamek/src/megamek/common/Game.java
Labels: Bug, Severity: Medium, Transportation

#6426 Issue 6389: Dropships in Movement phase cannot Assault Drop more units per turn than possible by repeatedly using the button
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
Labels: Bug, Severity: Medium, Transportation

#6432 Fix/princess should favor moving
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/IPathRanker.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/RankedPath.java
  megamek/src/megamek/common/Coords.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/MovePath.java
  megamek/src/megamek/common/event/GameEntityChangeEvent.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
Labels: Princess/AI, For New Dev Cycle

#6436 feat: minimap preview and selection option
  megamek/data/images/hexes/minimap/cyberpunk.theme
  megamek/data/images/hexes/minimap/darkula.theme
  megamek/data/images/hexes/minimap/defaultminimap.theme
  megamek/data/images/hexes/minimap/dreamy colors.theme
  megamek/data/images/hexes/minimap/earth and grass.theme
  megamek/data/images/hexes/minimap/gbc green.theme
  megamek/data/images/hexes/minimap/noctis.theme
  megamek/data/images/hexes/minimap/non-boolean.theme
  megamek/data/images/hexes/minimap/phosphor green.theme
  megamek/data/images/hexes/minimap/pink lemonade.theme
  megamek/data/images/hexes/minimap/pink world.theme
  megamek/data/images/hexes/minimap/rebirth.theme
  megamek/data/images/hexes/minimap/red amaranth.theme
  megamek/data/images/hexes/minimap/shades of green.theme
  megamek/data/images/hexes/minimap/solarized.theme
  megamek/data/images/hexes/minimap/synthwave.theme
  megamek/data/images/hexes/minimap/wood cabin.theme
  megamek/data/images/hexes/minimap/zone of battle.theme
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/baseComponents/FileNameComboBoxModel.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/minimap/BoardviewlessMinimap.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/common/Configuration.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: GUI

#6443 fix: ranked path fix
  megamek/src/megamek/client/bot/princess/RankedPath.java
  megamek/src/megamek/common/MovePath.java
Labels: Princess/AI

#6445 fix issue where closing window closes the unit display
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayDialog.java
Labels: Bug

#6446 feat: added sensor range on minimap, added facing arrow on minimap
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/boardview/FovHighlightingAndDarkening.java
  megamek/src/megamek/client/ui/swing/minimap/BoardviewlessMinimap.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/minimap/MinimapUnitSymbols.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: GUI, Improvement to Existing Feature

#6459 feat: quick and simple hazard check for hex
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/common/Hex.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
Labels: Princess/AI

#6462 From StringBuilder to Logger
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/InfantryPathRanker.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/ui/SharedUtility.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/ui/SharedUtilityTest.java
Labels: Performance

#6468 Fix/npe clicking on board no unit selected
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
Labels: Bug

#6469 fix: removes a double call for next-unit
  megamek/src/megamek/client/ui/swing/MovementDisplay.java
Labels: Bug

#6470 fix: minimap summary npe fix
  .gitignore
  megamek/src/megamek/client/ui/swing/boardview/BoardView.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/unitDisplay/ArmorPanel.java
  megamek/src/megamek/common/EntityVisibilityUtils.java
Labels: Bug

#6474 fix: makes Princess move way more than she otherwise would on no-contact
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
Labels: Princess/AI
