Repository MegaMek/megamek, pull requests merged in 2025-04, with the labels that each got.

#6823 Added Combat Sense and Combat Paralysis SPAs
  megamek/i18n/megamek/common/options/messages.properties
  megamek/src/megamek/client/ui/swing/CustomMekDialog.java
  megamek/src/megamek/common/AeroSpaceFighter.java
  megamek/src/megamek/common/BipedMek.java
  megamek/src/megamek/common/Game.java
  megamek/src/megamek/common/HandheldWeapon.java
  megamek/src/megamek/common/ITurnOrdered.java
  megamek/src/megamek/common/Infantry.java
  megamek/src/megamek/common/InitiativeRoll.java
  megamek/src/megamek/common/Jumpship.java
  megamek/src/megamek/common/Player.java
  megamek/src/megamek/common/ProtoMek.java
  megamek/src/megamek/common/QuadMek.java
  megamek/src/megamek/common/SmallCraft.java
  megamek/src/megamek/common/Tank.java
  megamek/src/megamek/common/Team.java
  megamek/src/megamek/common/TeleMissile.java
  megamek/src/megamek/common/TripodMek.java
  megamek/src/megamek/common/TurnOrdered.java
  megamek/src/megamek/common/autoresolve/acar/manager/InitiativeHelper.java
  megamek/src/megamek/common/options/OptionsConstants.java
  megamek/src/megamek/common/options/PilotOptions.java
  megamek/src/megamek/server/sbf/SBFGameManager.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/src/megamek/server/victory/EnemyCmdrDestroyedVictory.java
Labels: SPA (Special Pilot Abilities), Implementation of Missing Official Rule

#6762 Update Stalker STK-8S.mtf
  megamek/data/mekfiles/meks/3050U/Stalker STK-8S.mtf
Labels: Data

#6761 Stalker Jamison TechBase Fix: Mixed >>> Clan
  megamek/data/mekfiles/meks/3050U/Stalker STK-3F (Jamison).mtf
Labels: Data

#6760 Update Tomahawk II (Prime).mtf
  megamek/data/mekfiles/meks/3145/Clans/Tomahawk II (Prime).mtf
Labels: Data

#6759 Update Mackie MSK-6S introduction date
  megamek/data/mekfiles/meks/3075/Mackie MSK-6S.mtf
Labels: Data

#6835 Fixed issue with Ammo Counts showing 0 when configuring from Lobby
  megamek/src/megamek/client/ui/swing/CollapseWarning.java
  megamek/src/megamek/client/ui/swing/EquipChoicePanel.java
  megamek/src/megamek/client/ui/swing/panels/MunitionChoicePanel.java
  megamek/src/megamek/client/ui/swing/panels/WeaponAmmoChoicePanel.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/Mounted.java
Labels: Bug, Blocker

#6854 Moved `ImageUtilities` Into MegaMek Package
  megamek/src/megamek/utilities/ImageUtilities.java
Labels: Refactoring, Utility

#6856 Updated Logging, Clone Handling, and Added `toString` Methods
  megamek/src/megamek/client/ratgenerator/Parameters.java
  megamek/src/megamek/client/ui/swing/CancelAction.java
  megamek/src/megamek/client/ui/swing/CloseAction.java
  megamek/src/megamek/client/ui/swing/OkayAction.java
Labels: Refactoring

#6859 Issue Megameklab#1818: Correct "armor_tech" to "armor_tech_level" when applicable
  megamek/src/megamek/common/loaders/BLKAeroSpaceFighterFile.java
  megamek/src/megamek/common/loaders/BLKConvFighterFile.java
  megamek/src/megamek/common/loaders/BLKDropshipFile.java
  megamek/src/megamek/common/loaders/BLKFile.java
  megamek/src/megamek/common/loaders/BLKJumpshipFile.java
  megamek/src/megamek/common/loaders/BLKMekFile.java
  megamek/src/megamek/common/loaders/BLKProtoMekFile.java
  megamek/src/megamek/common/loaders/BLKSmallCraftFile.java
  megamek/src/megamek/common/loaders/BLKSpaceStationFile.java
  megamek/src/megamek/common/loaders/BLKTankFile.java
  megamek/src/megamek/common/loaders/BLKVTOLFile.java
  megamek/src/megamek/common/loaders/BLKWarshipFile.java
Labels: Bug

#6869 Added @Nullable to `getEngine`
  megamek/src/megamek/common/Entity.java
Labels: Refactoring

#6877 Added Missing Camo for MekHQ New Player Quickstart
  megamek/data/images/camo/Misc/The Learning Ropes.png
Labels: Data

#6834 feat: slightly better serializer for unit actions and state, added attack action too
  megamek/src/megamek/ai/dataset/BoardData.java
  megamek/src/megamek/ai/dataset/BoardDataSerializer.java
  megamek/src/megamek/ai/dataset/EntityDataMap.java
  megamek/src/megamek/ai/dataset/EntityDataSerializer.java
  megamek/src/megamek/ai/dataset/GameData.java
  megamek/src/megamek/ai/dataset/GameDataSerializer.java
  megamek/src/megamek/ai/dataset/MapSettingsData.java
  megamek/src/megamek/ai/dataset/MapSettingsDataSerializer.java
  megamek/src/megamek/ai/dataset/PlanetaryConditionsData.java
  megamek/src/megamek/ai/dataset/PlanetaryConditionsDataSerializer.java
  megamek/src/megamek/ai/dataset/UnitAction.java
  megamek/src/megamek/ai/dataset/UnitActionField.java
  megamek/src/megamek/ai/dataset/UnitActionSerde.java
  megamek/src/megamek/ai/dataset/UnitActionSerializer.java
  megamek/src/megamek/ai/dataset/UnitAttack.java
  megamek/src/megamek/ai/dataset/UnitAttackSerializer.java
  megamek/src/megamek/ai/dataset/UnitState.java
  megamek/src/megamek/ai/dataset/UnitStateField.java
  megamek/src/megamek/ai/dataset/UnitStateSerde.java
  megamek/src/megamek/ai/dataset/UnitStateSerializer.java
  megamek/src/megamek/ai/utility/EntityFeatureUtils.java
  megamek/src/megamek/ai/utility/Memory.java
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/GameDatasetLogger.java
  megamek/unittests/megamek/common/EntityFeatureUtilsTest.java
Labels: Princess/AI

#6875 Issue MekHQ#6619: Move `RestoreUnitAction::copyC3Networks` from MekHQ to MegaMek's `C3Utils`
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/util/C3Util.java
Labels: Bug, MHQ-origin MM Issues, Severity: Medium

#6857 Fixed Port Validation (Sentry)
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/gameConnectionDialogs/AbstractGameConnectionDialog.java
Labels: Bug, Severity: Low

#6868 Fix #6867: Excluded Infantry Attack From Edit Unit Damage Dialog
  megamek/src/megamek/client/ui/swing/UnitEditorDialog.java
Labels: Bug, Severity: Low

#6842 Seraph quirk fix for bug #6508
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-O Invictus.mtf
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-OA Dominus.mtf
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-OB Infernus.mtf
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-OC Comminus.mtf
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-OD Luminos.mtf
  megamek/data/mekfiles/meks/3075/Seraph C-SRP-OE Eminus.mtf
  megamek/data/mekfiles/meks/Jihad Secrets/Seraph C-SRP-O Caelestis.mtf
  megamek/data/mekfiles/meks/Turning Points/JTP Sian/Seraph C-SRP-O Ravana.mtf
  megamek/data/mekfiles/meks/Wolf and Blake/Seraph C-SRP-O Havalah.mtf
Labels: Data

#6891 Fix version comparisons now that isExtra is never null
  megamek/src/megamek/Version.java
Labels: Bug, Blocker, MHQ-origin MM Issues

#6898 feat: dataset logger opt-out reset
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: Princess/AI, PACAR

#6900 Issue #6899: Release is no longer in version, but patch is
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
Labels: Bug, Blocker, Nightly

#6905 Issue #6904: Flak attacks must target entities, that must be considered when princess is targeting
  megamek/src/megamek/client/bot/princess/ArtilleryTargetingControl.java
Labels: Bug, Princess/AI, Nightly, Severity: High, Artillery

#6908 Homing Artillery should work direct fire when targeting a hex
  megamek/src/megamek/common/actions/WeaponAttackAction.java
Labels: Bug

#6928 Issue #6918: If `target` is not null, but it's an entity, and the entity is no longer in the game, then it's fled/dead
  megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java
Labels: Bug, Severity: Medium, Artillery

#6864 Added Heroic and Legendary Skill Levels
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: Implementation of Missing Official Rule

#6949 Revert "Added Heroic and Legendary Skill Levels"
  megamek/src/megamek/common/enums/SkillLevel.java
Labels: Refactoring

#6945 fix: uses bot skill generator when creating armies
  megamek/docs/history.txt
  megamek/src/megamek/client/ui/swing/RandomArmyDialog.java
Labels: Bug

#6936 Fix: Added Missing Nullable Tag to getExtraDataValue
  megamek/src/megamek/common/Crew.java
Labels: Refactoring
