Repository MegaMek/megamek, pull requests merged in 2025-02, with the labels that each got.

#6478 fix: a couple of signs in the wrong place on the scoring equation
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
Labels: Bug, Princess/AI

#6477 Fix 5590: princess firing on 13s due to intervening trees, etc.
  megamek/src/megamek/client/bot/princess/FireControl.java
  megamek/src/megamek/client/bot/princess/WeaponFireInfo.java
  megamek/src/megamek/common/actions/WeaponAttackAction.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
Labels: Princess/AI

#6479 fix: removes an argument and early exit added by mistake to hyperagreression
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/InfantryPathRanker.java
Labels: Bug, Princess/AI

#6485 fix: fixes html tags showing on tooltips
  megamek/src/megamek/client/ui/swing/util/UIUtil.java
Labels: Bug, GUI

#6484 fix: stop dropShadow from being calculated for force display tree
  megamek/src/megamek/client/ui/swing/forceDisplay/ForceDisplayMekTreeRenderer.java
  megamek/src/megamek/client/ui/swing/tileset/EntityImage.java
  megamek/src/megamek/client/ui/swing/tileset/FighterSquadronIcon.java
  megamek/src/megamek/client/ui/swing/tileset/TilesetManager.java
Labels: Bug, Performance

#6476 Issue 6303: RFE - Hazardous Liquid Pool
  megamek/data/images/hexes/StandardIncludes/StandardHazardousLiquid.tileinc
  megamek/data/images/hexes/atmospheric.tileset
  megamek/data/images/hexes/bw_atmospheric.tileset
  megamek/data/images/hexes/classic.tileset
  megamek/data/images/hexes/hazardous_liquid/green1_toxic_water.png
  megamek/data/images/hexes/hazardous_liquid/green2_toxic_water.png
  megamek/data/images/hexes/hq_atmospheric.tileset
  megamek/data/images/hexes/hq_isometric.tileset
  megamek/data/images/hexes/hq_saxarba.tileset
  megamek/data/images/hexes/isometric.tileset
  megamek/data/images/hexes/largeTextures.tileset
  megamek/data/images/hexes/saxarba.tileset
  megamek/i18n/megamek/client/messages.properties
  megamek/i18n/megamek/common/messages.properties
  megamek/i18n/megamek/common/report-messages.properties
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/ui/SharedUtility.java
  megamek/src/megamek/common/Terrain.java
  megamek/src/megamek/common/Terrains.java
  megamek/src/megamek/common/enums/HazardousLiquidPoolType.java
  megamek/src/megamek/common/util/HazardousLiquidPoolUtil.java
  megamek/src/megamek/server/ServerHelper.java
  megamek/src/megamek/server/totalwarfare/MovePathHandler.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
Labels: (RFE) Enhancement, For New Dev Cycle

#6475 Feat/refactor flags
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/common/AmmoType.java
  megamek/src/megamek/common/AmmoTypeFlag.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/EquipmentBitSet.java
  megamek/src/megamek/common/EquipmentFlag.java
  megamek/src/megamek/common/EquipmentType.java
  megamek/src/megamek/common/Mek.java
  megamek/src/megamek/common/MiscType.java
  megamek/src/megamek/common/MiscTypeFlag.java
  megamek/src/megamek/common/WeaponType.java
  megamek/src/megamek/common/WeaponTypeFlag.java
  megamek/src/megamek/common/pathfinder/CachedEntityState.java
  megamek/src/megamek/common/verifier/TestAdvancedAerospace.java
  megamek/src/megamek/common/verifier/TestSmallCraft.java
  megamek/src/megamek/common/verifier/TestSupportVehicle.java
  megamek/src/megamek/common/weapons/bayweapons/CapitalMDBayWeapon.java
  megamek/src/megamek/common/weapons/other/CLLaserAMS.java
  megamek/src/megamek/common/weapons/other/ISLaserAMS.java
  megamek/src/megamek/common/weapons/unofficial/ISLaserAMSTHB.java
  megamek/unittests/megamek/client/bot/princess/FireControlTest.java
Labels: Performance, For New Dev Cycle

#6490 Added Infantry `Mob` Unit Files
  megamek/data/mekfiles/infantry/Mobs/Mob (Huge).blk
  megamek/data/mekfiles/infantry/Mobs/Mob (Large).blk
  megamek/data/mekfiles/infantry/Mobs/Mob (Medium).blk
  megamek/data/mekfiles/infantry/Mobs/Mob (Small).blk
Labels: Data, Unofficial

#6495 feat: add gif writer to task and in the static start
  build.gradle
  megamek/build.gradle
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineFlag.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/utilities/GifWriter.java
Labels: Utility

#6498 feat: log bot actions for debugging
  megamek/src/megamek/client/bot/BotLogger.java
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/RankedPath.java
Labels: Princess/AI

#6486 AI Toy - Piracy, new behaviors, and a new test platform to build upon
  megamek/build.gradle
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/BehaviorSettingsFactory.java
  megamek/src/megamek/client/bot/princess/CoverageValidator.java
  megamek/src/megamek/client/bot/princess/EnemyTracker.java
  megamek/src/megamek/client/bot/princess/FireControl.java
  megamek/src/megamek/client/bot/princess/HonorUtil.java
  megamek/src/megamek/client/bot/princess/IHonorUtil.java
  megamek/src/megamek/client/bot/princess/PathRanker.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/SwarmCenterManager.java
  megamek/src/megamek/client/bot/princess/SwarmContext.java
  megamek/src/megamek/client/bot/princess/UtilityPathRanker.java
  megamek/src/megamek/client/ui/dialogs/BotConfigDialog.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/common/Compute.java
  megamek/src/megamek/common/Coords.java
  megamek/src/megamek/common/CubeCoords.java
  megamek/src/megamek/common/preference/ClientPreferences.java
  megamek/src/megamek/common/util/SerializationHelper.java
  megamek/src/megamek/server/Server.java
  megamek/src/megamek/server/commands/GamemasterServerCommand.java
  megamek/src/megamek/server/commands/OrbitalBombardmentCommand.java
  megamek/src/megamek/utilities/QuickGameRunner.java
  megamek/testresources/megamek/client/bot/behaviorSettings.xml
  megamek/unittests/megamek/client/BasicGameTest.java
  megamek/unittests/megamek/client/GameThread.java
  megamek/unittests/megamek/client/bot/princess/BasicPathRankerTest.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsFactoryTest.java
  megamek/unittests/megamek/client/bot/princess/BehaviorSettingsFactoryTestConstants.java
Labels: Princess/AI

#6504 Feat/minimap move path
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
Labels: GUI

#6523 feat: uses median of the 5 closest enemies for facing mod
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/common/Coords.java
  megamek/unittests/megamek/common/CoordsTest.java
Labels: Princess/AI

#6521 Feat: More ai tools
  megamek/build.gradle
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/ai/dataset/ActionAndState.java
  megamek/src/megamek/ai/dataset/DatasetParser.java
  megamek/src/megamek/ai/dataset/TrainingDataset.java
  megamek/src/megamek/ai/dataset/TsvSerde.java
  megamek/src/megamek/ai/dataset/UnitAction.java
  megamek/src/megamek/ai/dataset/UnitActionField.java
  megamek/src/megamek/ai/dataset/UnitActionSerde.java
  megamek/src/megamek/ai/dataset/UnitState.java
  megamek/src/megamek/ai/dataset/UnitStateField.java
  megamek/src/megamek/ai/dataset/UnitStateSerde.java
  megamek/src/megamek/ai/optimizer/BasicPathRankerCostFunction.java
  megamek/src/megamek/ai/optimizer/BehaviorState.java
  megamek/src/megamek/ai/optimizer/Checkpoint.java
  megamek/src/megamek/ai/optimizer/CostFunction.java
  megamek/src/megamek/ai/optimizer/CostFunctionChooser.java
  megamek/src/megamek/ai/optimizer/ExtendedCostFunction.java
  megamek/src/megamek/ai/optimizer/ModelParameter.java
  megamek/src/megamek/ai/optimizer/ParameterOptimizer.java
  megamek/src/megamek/ai/optimizer/Parameters.java
  megamek/src/megamek/ai/optimizer/UtilityPathRankerCostFunction.java
  megamek/src/megamek/client/bot/princess/BasicPathRanker.java
  megamek/src/megamek/client/bot/princess/BehaviorSettings.java
  megamek/src/megamek/client/bot/princess/InfantryPathRanker.java
  megamek/src/megamek/client/bot/princess/SwarmContext.java
  megamek/src/megamek/client/bot/princess/UtilityPathRanker.java
  megamek/src/megamek/common/Coords.java
  megamek/src/megamek/common/CubeCoords.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/GameDatasetLogger.java
  megamek/src/megamek/common/Hex.java
  megamek/src/megamek/common/MovePath.java
  megamek/src/megamek/common/MoveStep.java
  megamek/src/megamek/common/Terrains.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineFlag.java
  megamek/src/megamek/common/commandline/MegaMekCommandLineParser.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/src/megamek/utilities/GifWriter.java
  megamek/src/megamek/utilities/PrincessFineTuning.java
Labels: Princess/AI, Utility

#6527 feat/gif your game
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/GUIPreferences.java
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
  megamek/src/megamek/client/ui/swing/minimap/MinimapUnitSymbols.java
  megamek/src/megamek/utilities/GifWriter.java
  megamek/src/megamek/utilities/GifWriterThread.java
Labels: GUI

#6529 fix: check if it is a narcpod before trying to access getPosition
  megamek/src/megamek/common/GameDatasetLogger.java
Labels: Bug, Princess/AI

#6533 feat: hide acar on the front of the megamek lounge
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/CommonSettingsDialog.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/common/preference/ClientPreferences.java
Labels: GUI, ACAR

#6549 Issue 6540: Towing from MM lobby
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/Client.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/ui/swing/DeploymentDisplay.java
  megamek/src/megamek/client/ui/swing/TowLinkWarning.java
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyActions.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyErrors.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekCellFormatter.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopup.java
  megamek/src/megamek/client/ui/swing/lobby/LobbyMekPopupActions.java
  megamek/src/megamek/common/Entity.java
  megamek/src/megamek/common/net/enums/PacketCommand.java
  megamek/src/megamek/server/totalwarfare/TWGameManager.java
  megamek/unittests/megamek/client/ui/swing/TowLinkWarningTest.java
Labels: (RFE) Enhancement, Transportation, Improvement to Existing Feature

#6589 feat: adds bot waypoint control to send certain units towards certain positions on the map
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/bot/BotClient.java
  megamek/src/megamek/client/bot/ChatProcessor.java
  megamek/src/megamek/client/bot/princess/ChatCommands.java
  megamek/src/megamek/client/bot/princess/PathEnumerator.java
  megamek/src/megamek/client/bot/princess/Princess.java
  megamek/src/megamek/client/bot/princess/UnitBehavior.java
  megamek/src/megamek/client/ui/swing/MapMenu.java
  megamek/src/megamek/common/Coords.java
  megamek/src/megamek/common/MovePath.java
  megamek/src/megamek/common/pathfinder/BoardClusterTracker.java
  megamek/src/megamek/common/pathfinder/LongestPathFinder.java
Labels: Princess/AI

#6590 fix: make ejected and other removed units show up transparent on minimap
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
Labels: GUI

#6592 fix: small fixes that were missed from a previous code review
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
Labels: Severity: Medium

#6591 feat: MMLogger using parametrized message and string formatter
  megamek/src/megamek/MegaMek.java
  megamek/src/megamek/Version.java
  megamek/src/megamek/client/ui/swing/ClientGUI.java
  megamek/src/megamek/client/ui/swing/MegaMekGUI.java
  megamek/src/megamek/logging/MMLogger.java
  megamek/unittests/megamek/logging/MMLoggerTest.java
Labels: Tests

#6596 feat: disable ACAR for all clients if using real-blind-drop
  megamek/src/megamek/client/ui/swing/lobby/ChatLounge.java
Labels: ACAR

#6598 fix: actually I fixed everything that there was to fix on the minimap
  megamek/i18n/megamek/client/messages.properties
  megamek/src/megamek/client/ui/swing/minimap/Minimap.java
Labels: Bug

#6600 fix: fix a parsing error and turns it into a singleton using enum
  megamek/src/megamek/client/generator/RandomCallsignGenerator.java
Labels: Bug
